# Feature Engineering 1.1.1 Notebook

Using data from 1.0 exploratory data analysis notebook; first iteration of feature engineering

In [208]:
from src.utils import data_utils
import pandas as pd
import numpy as np

In [209]:
data = data_utils.load_data("../data/interim/eda_1_0_1_df.pkl")

In [210]:
data.head()

,"(participants_age, modified_dem_0110)","(participants_sex, dem_0500)","(height_in_inches, dem_0610)","(weight_in_pounds, dem_0700)","(body_mass_index_(bmi), dem_0800)","(number_of_people_living_in_your_household, bthbts_0500)","(number_of_children_aged_5_years_or_younger_living_in_your_household, bthbts_0510)","(number_of_children_aged_6_17_living_in_your_household, bthbts_0520)","(number_of_adults_aged_18_59_living_in_your_household, bthbts_0530)","(number_of_adults_aged_60_years_of_older_living_in_your_household, bthbts_0540)",...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,0,0,2,2,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,0,2,1,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,0,0,0,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,1,0,2,0,...,0,0,0,4,4,3,3,1,0,1.3

In [211]:
fe_data = data.copy()

In [212]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data):
    # Rename column ('participants_age', 'modified_dem_0110') to 'age'
    fe_data = fe_data.rename(columns={('participants_age', 'modified_dem_0110'): 'age'})
    # Rename column ('participants_sex', 'dem_0500') to 'sex'
    fe_data = fe_data.rename(columns={('participants_sex', 'dem_0500'): 'sex'})
    # Rename column ('height_in_inches', 'dem_0610') to 'height_inches'
    fe_data = fe_data.rename(columns={('height_in_inches', 'dem_0610'): 'height_inches'})
    # Rename column ('weight_in_pounds', 'dem_0700') to 'weight_pounds'
    fe_data = fe_data.rename(columns={('weight_in_pounds', 'dem_0700'): 'weight_pounds'})
    # Rename column ('body_mass_index_(bmi)', 'dem_0800') to 'bmi'
    fe_data = fe_data.rename(columns={('body_mass_index_(bmi)', 'dem_0800'): 'bmi'})
    return fe_data

fe_data_clean = clean_data(fe_data.copy())
fe_data_clean.head()

,age,sex,height_inches,weight_pounds,bmi,"(number_of_people_living_in_your_household, bthbts_0500)","(number_of_children_aged_5_years_or_younger_living_in_your_household, bthbts_0510)","(number_of_children_aged_6_17_living_in_your_household, bthbts_0520)","(number_of_adults_aged_18_59_living_in_your_household, bthbts_0530)","(number_of_adults_aged_60_years_of_older_living_in_your_household, bthbts_0540)",...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,0,0,2,2,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,0,2,1,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,0,0,0,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,1,0,2,0,...,0,0,0,4,4,3,3,1,0,1.3

In [213]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean):
    # Rename column ('number_of_people_living_in_your_household', 'bthbts_0500') to 'num_people_in_house'
    fe_data_clean = fe_data_clean.rename(columns={('number_of_people_living_in_your_household', 'bthbts_0500'): 'num_people_in_house'})
    # Drop columns: '('number_of_children_aged_5_years_or_younger_living_in_your_household', 'bthbts_0510')', '('number_of_children_aged_6_17_living_in_your_household', 'bthbts_0520')' and 2 other columns
    fe_data_clean = fe_data_clean.drop(columns=[('number_of_children_aged_5_years_or_younger_living_in_your_household', 'bthbts_0510'), ('number_of_children_aged_6_17_living_in_your_household', 'bthbts_0520'), ('number_of_adults_aged_18_59_living_in_your_household', 'bthbts_0530'), ('number_of_adults_aged_60_years_of_older_living_in_your_household', 'bthbts_0540')])
    return fe_data_clean

fe_data_clean_1 = clean_data(fe_data_clean.copy())
fe_data_clean_1.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,"(days_per_week_in_school_or_work, sched_9900)","(irregular_schedule, sched_9910)","(time_school_or_work_starts, sched_9910)","(time_school_or_work_ends, sched_9920)",...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaT,NaT,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,1900-01-01 08:00:00,1900-01-01 17:00:00,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,1900-01-01 07:00:00,1900-01-01 19:00:00,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,1900-01-01 06:00:00,1900-01-01 20:00:00,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,1900-01-01 08:15:00,1900-01-01 17:30:00,...,0,0,0,4,4,3,3,1,0,1.3

In [214]:
""" 
encoding work/school start/end time
turn it into number of hours before/after 9am/5pm 
"""

work_start_times = fe_data_clean_1[('time_school_or_work_starts', 'sched_9910')].dt.time
work_end_times = fe_data_clean_1[('time_school_or_work_ends', 'sched_9920')].dt.time


nine_am = pd.to_datetime("09:00:00").time()
five_pm = pd.to_datetime("17:00:00").time()

def time_diff_in_hours(time1, time2):
    datetime1 = pd.to_datetime(time1, format='%H:%M:%S')
    datetime2 = pd.to_datetime(time2, format='%H:%M:%S')
    diff = (datetime1 - datetime2).total_seconds() / 3600
    return diff

fe_data_clean_1[('work_start_time_diff_from_9am', 'sched_9910')] = work_start_times.apply(lambda x: time_diff_in_hours(x, nine_am))
fe_data_clean_1[('work_end_time_diff_from_5pm', 'sched_9920')] = work_end_times.apply(lambda x: time_diff_in_hours(x, five_pm))

In [215]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean_1):
    # Rename column ('time_school_or_work_starts', 'sched_9910') to 'sw_9am_diff'
    fe_data_clean_1 = fe_data_clean_1.rename(columns={('time_school_or_work_starts', 'sched_9910'): 'sw_9am_diff'})
    # Rename column ('time_school_or_work_ends', 'sched_9920') to 'sw_5pm_end_diff'
    fe_data_clean_1 = fe_data_clean_1.rename(columns={('time_school_or_work_ends', 'sched_9920'): 'sw_5pm_end_diff'})
    # Rename column 'sw_9am_diff' to 'sw_9am_start_diff'
    fe_data_clean_1 = fe_data_clean_1.rename(columns={'sw_9am_diff': 'sw_9am_start_diff'})
    return fe_data_clean_1

fe_data_clean_2 = clean_data(fe_data_clean_1.copy())
fe_data_clean_2.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,"(days_per_week_in_school_or_work, sched_9900)","(irregular_schedule, sched_9910)",sw_9am_start_diff,sw_5pm_end_diff,...,"(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)","(work_start_time_diff_from_9am, sched_9910)","(work_end_time_diff_from_5pm, sched_9920)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaT,NaT,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3,NaN,NaN
1,30,F,67,188.0,29.4,4,<NA>,False,1900-01-01 08:00:00,1900-01-01 17:00:00,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4,-1.00,0.0
2,30,F,67,165.0,25.8,3,3,True,1900-01-01 07:00:00,1900-01-01 19:00:00,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,-2.00,2.0
3,42,M,64,156.0,26.8,0,7,True,1900-01-01 06:00:00,1900-01-01 20:00:00,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9,-3.00,3.0
4,36,M,63,255.0,45.2,3,5,True,1900-01-01 08:15:00,1900-01-01 17:30:00,...,0,4,4,3,3,1,0,1.3,-0.75,0.5

In [216]:
fe_data_clean_2['sw_9am_start_diff'] = fe_data_clean_2[('work_start_time_diff_from_9am', 'sched_9910')]
fe_data_clean_2['sw_5pm_end_diff'] = fe_data_clean_2[('work_end_time_diff_from_5pm', 'sched_9920')]

fe_data_clean_2 = fe_data_clean_2.drop(columns=[('work_start_time_diff_from_9am', 'sched_9910'), ('work_end_time_diff_from_5pm', 'sched_9920')])

In [217]:
fe_data_clean_2.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,"(days_per_week_in_school_or_work, sched_9900)","(irregular_schedule, sched_9910)",sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [218]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean_2):
    # Rename column ('days_per_week_in_school_or_work', 'sched_9900') to 'sw_num_days_per_week'
    fe_data_clean_2 = fe_data_clean_2.rename(columns={('days_per_week_in_school_or_work', 'sched_9900'): 'sw_num_days_per_week'})
    # Rename column ('irregular_schedule', 'sched_9910') to 'irreg_sched'
    fe_data_clean_2 = fe_data_clean_2.rename(columns={('irregular_schedule', 'sched_9910'): 'irreg_sched'})
    return fe_data_clean_2

fe_data_clean_3 = clean_data(fe_data_clean_2.copy())
fe_data_clean_3.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [219]:
"""
Cell generated by Data Wrangler.
Renaming NOSE survey columns and dropping the total column as it is justa sum and x5 Multi of all results 
"""
def clean_data(fe_data_clean_3):
    # Rename column ('nasal_congestion_or_stuffiness', 'nose_0100') to 'nasal_congestion_stuffiness_nose'
    fe_data_clean_3 = fe_data_clean_3.rename(columns={('nasal_congestion_or_stuffiness', 'nose_0100'): 'nasal_congestion_stuffiness_nose'})
    # Rename column ('nasal_blockage_or_obstruction', 'nose_0200') to 'nasal_blockage_obstr_nose'
    fe_data_clean_3 = fe_data_clean_3.rename(columns={('nasal_blockage_or_obstruction', 'nose_0200'): 'nasal_blockage_obstr_nose'})
    # Rename column ('trouble_breathing_through_nose', 'nose_0300') to 'troub_brth_nose'
    fe_data_clean_3 = fe_data_clean_3.rename(columns={('trouble_breathing_through_nose', 'nose_0300'): 'troub_brth_nose'})
    # Rename column ('trouble_sleeping', 'nose_0400') to 'troub_slp_nose'
    fe_data_clean_3 = fe_data_clean_3.rename(columns={('trouble_sleeping', 'nose_0400'): 'troub_slp_nose'})
    # Rename column ('unable_to_get_enough_air_through_nose_during_exercise_or_exertion', 'nose_0500') to 'not_enough_air_excercise_nose'
    fe_data_clean_3 = fe_data_clean_3.rename(columns={('unable_to_get_enough_air_through_nose_during_exercise_or_exertion', 'nose_0500'): 'not_enough_air_excercise_nose'})
    # Drop column: '('nose_total_score', 'nose_0600')'
    fe_data_clean_3 = fe_data_clean_3.drop(columns=[('nose_total_score', 'nose_0600')])
    return fe_data_clean_3

fe_data_clean_4 = clean_data(fe_data_clean_3.copy())
fe_data_clean_4.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [220]:
""" 
map bed_partners to binary; based on data dicitonary only 3 adn 4 mean directly having
parter or child in bed, others are just in different rooms or variations.
now boolean yes or no
"""

bed_partners = fe_data_clean_4[('bed_partner_or_roommate', 'bthbts_0100')]
fe_data_clean_4 = fe_data_clean_4.rename(columns={('bed_partner_or_roommate', 'bthbts_0100'): 'bed_partners'})

bed_partners_mapping = {
    0: 'False',
    1: 'False',
    2: 'False',
    3: 'True',
    4: 'True',}

fe_data_clean_4['bed_partners'] = fe_data_clean_4['bed_partners'].map(bed_partners_mapping)

In [221]:
fe_data_clean_4.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [222]:
"""
Cell generated by Data Wrangler.
dropped this column because i fucked it when encoding (wasnt supposed to be boolean) but i think i would dorp anyway
"""
def clean_data(fe_data_clean_4):
    # Drop column: '('exercise_time_frame', 'soclhx_0520')'
    fe_data_clean_4 = fe_data_clean_4.drop(columns=[('exercise_time_frame', 'soclhx_0520')])
    return fe_data_clean_4

fe_data_clean_5 = clean_data(fe_data_clean_4.copy())
fe_data_clean_5.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [223]:
earlymorning_mapping = {
    0: "early morning",
    1: "late morning",
    2: "early afternoon",
    3: "late afternoon",
    4: "between dinner and bedtime",
    5: "varies",
}

fe_data_clean_5 = fe_data_clean_5.rename(
    columns={("exercise_time_of_day", "soclhx_0600"): "exercise_time_of_day"}
)
fe_data_clean_5 = fe_data_clean_5.rename(
    columns={("exercise_rarely_or_never", "soclhx_0501"): "exercise_rarely_or_never"}
 )

fe_data_clean_5["exercise_time_of_day"] = fe_data_clean_5["exercise_time_of_day"].map(
    earlymorning_mapping
)


fe_data_clean_5.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [224]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean_5):
    # Change column type to string for column: 'exercise_rarely_or_never'
    fe_data_clean_5 = fe_data_clean_5.astype({'exercise_rarely_or_never': 'string'})
    return fe_data_clean_5

fe_data_clean_6 = clean_data(fe_data_clean_5.copy())
fe_data_clean_6.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [225]:
is_na = fe_data_clean_6["exercise_rarely_or_never"].isna()
is_true = fe_data_clean_6["exercise_rarely_or_never"].fillna('').eq('True')

fe_data_clean_6["exercise_rarely_or_never"] = np.where(
    is_na,
    np.nan,
    np.where(
        is_true,
        'rarely_or_never',
        fe_data_clean_6["exercise_time_of_day"]
    )
)

fe_data_clean_6.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [226]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean_6):
    # Drop column: 'exercise_time_of_day'
    fe_data_clean_6 = fe_data_clean_6.drop(columns=['exercise_time_of_day'])
    # Rename column 'exercise_rarely_or_never' to 'exercise_amt_or_time'
    fe_data_clean_6 = fe_data_clean_6.rename(columns={'exercise_rarely_or_never': 'exercise_amt_or_time'})
    return fe_data_clean_6

fe_data_clean_7 = clean_data(fe_data_clean_6.copy())
fe_data_clean_7.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [227]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean_7):
    # Drop column: '('alcohol_consumption_number_of_times', 'soclhx_0700')'
    fe_data_clean_7 = fe_data_clean_7.drop(columns=[('alcohol_consumption_number_of_times', 'soclhx_0700')])
    # Drop column: '('alcohol_consumption_time_frame', 'soclhx_0710')'
    fe_data_clean_7 = fe_data_clean_7.drop(columns=[('alcohol_consumption_time_frame', 'soclhx_0710')])
    # Rename column ('alcohol_consumption_rarely_or_never', 'soclhx_0701') to 'alcohol_consumption_rarely_or_never'
    fe_data_clean_7 = fe_data_clean_7.rename(columns={('alcohol_consumption_rarely_or_never', 'soclhx_0701'): 'alcohol_consumption_rarely_or_never'})
    # Drop column: '('alcohol_consumption_number_of_servings_per_day', 'soclhx_0730')'
    fe_data_clean_7 = fe_data_clean_7.drop(columns=[('alcohol_consumption_number_of_servings_per_day', 'soclhx_0730')])
    return fe_data_clean_7

fe_data_clean_8 = clean_data(fe_data_clean_7.copy())
fe_data_clean_8.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [228]:
"""
caffeine column merging; if rarely or never drink caffeine then put daily servings to zero.
"""

fe_data_clean_8 = fe_data_clean_8.rename(
    columns={
        (
            "caffeine_consumption_number_of_servings_per_day",
            "soclhx_0900",
        ): "daily_caffeine_servings",
        (
            ("caffeine_consumption_rarely_or_never", "soclhx_0901")
        ): "caffeine_consumption_rarely_or_never",
    }
)

is_true = fe_data_clean_8["caffeine_consumption_rarely_or_never"].fillna(False).eq(True)
is_na = fe_data_clean_8["daily_caffeine_servings"].isna() & ~is_true

fe_data_clean_8["daily_caffeine_servings"] = np.where(
    is_true,
    0,
    np.where(
        is_na,
        np.nan,
        fe_data_clean_8["daily_caffeine_servings"]
    )
)

fe_data_clean_8 = fe_data_clean_8.drop(columns=["caffeine_consumption_rarely_or_never"])

fe_data_clean_8.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [229]:
""" 
encoding caffeine time of last consumption as hours before average bedtime
TODO: once you get to bedtime variables come back and do this :) 
"""

' \nencoding caffeine time of last consumption as hours before average bedtime\nTODO: once you get to bedtime variables come back and do this :) \n'

In [230]:
"""
Cell generated by Data Wrangler.
removed cigarette smoking columsn right now becasue they are jank and mostly empty and there might be more. might come back to this later.
"""
def clean_data(fe_data_clean_8):
    # Drop column: '('cigarette_smoking_age_started', 'soclhx_1200')'
    fe_data_clean_8 = fe_data_clean_8.drop(columns=[('cigarette_smoking_age_started', 'soclhx_1200')])
    # Drop column: '('cigarette_smoking_number_of_cigarettes', 'soclhx_1300')'
    fe_data_clean_8 = fe_data_clean_8.drop(columns=[('cigarette_smoking_number_of_cigarettes', 'soclhx_1300')])
    # Drop column: '('cigarette_smoking_time_frame', 'soclhx_1310')'
    fe_data_clean_8 = fe_data_clean_8.drop(columns=[('cigarette_smoking_time_frame', 'soclhx_1310')])
    # Drop column: '('cigarette_smoking_age_stopped', 'soclhx_1400')'
    fe_data_clean_8 = fe_data_clean_8.drop(columns=[('cigarette_smoking_age_stopped', 'soclhx_1400')])
    return fe_data_clean_8

fe_data_clean_9 = clean_data(fe_data_clean_8.copy())
fe_data_clean_9.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [231]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean_9):
    # Drop column: '('street_or_recreational_drugs_consumption_age_started', 'soclhx_1700')'
    fe_data_clean_9 = fe_data_clean_9.drop(columns=[('street_or_recreational_drugs_consumption_age_started', 'soclhx_1700')])
    # Drop column: '('street_or_recreational_drugs_consumption_age_stopped', 'soclhx_1800')'
    fe_data_clean_9 = fe_data_clean_9.drop(columns=[('street_or_recreational_drugs_consumption_age_stopped', 'soclhx_1800')])
    # Rename column ('street_or_recreational_drugs_consumption_ever', 'soclhx_1500') to 'street_drug_consume_status'
    fe_data_clean_9 = fe_data_clean_9.rename(columns={('street_or_recreational_drugs_consumption_ever', 'soclhx_1500'): 'street_drug_consume_status'})
    return fe_data_clean_9

fe_data_clean_10 = clean_data(fe_data_clean_9.copy())
fe_data_clean_10.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [232]:
""" 
mapping this variable to be one hot encoded eventually and interpretability prolly
"""

street_drug_mapping = {
    0: 'never',
    1: 'former user',
    2: 'current user',
    3: 'chose no answer'
}

fe_data_clean_10['street_drug_consume_status'] = fe_data_clean_10['street_drug_consume_status'].map(street_drug_mapping)

fe_data_clean_10.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [233]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean_10):
    # Rename column ('heartburn_or_belching_after_going_to_bed_days_per_week', 'osa_0100') to 'heartburn_belching_after_bed_freq'
    fe_data_clean_10 = fe_data_clean_10.rename(columns={('heartburn_or_belching_after_going_to_bed_days_per_week', 'osa_0100'): 'heartburn_belching_after_bed_freq'})
    # Rename column ('perspire_heavily_during_the_night_days_per_week', 'osa_0200') to 'heavy_sweat_during_sleep_freq'
    fe_data_clean_10 = fe_data_clean_10.rename(columns={('perspire_heavily_during_the_night_days_per_week', 'osa_0200'): 'heavy_sweat_during_sleep_freq'})
    # Rename column ('dry_and/or_irritated_eyes', 'osa_0300') to 'dry_irritated_eyes_freq'
    fe_data_clean_10 = fe_data_clean_10.rename(columns={('dry_and/or_irritated_eyes', 'osa_0300'): 'dry_irritated_eyes_freq'})
    return fe_data_clean_10

fe_data_clean_11 = clean_data(fe_data_clean_10.copy())
fe_data_clean_11.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [234]:
""" 
according to data dictionary 5 on these scales (5dk) 5 is also a dont know so i will
think about how to handle that but now will hold off
"""

' \naccording to data dictionary 5 on these scales (5dk) 5 is also a dont know so i will\nthink about how to handle that but now will hold off\n'

In [235]:
"""
Cell generated by Data Wrangler.
Renamed PHQ and GAD columns for interprability; did not drop total scores as I want to
see feature importance and correlation on further runs for now
"""
def clean_data(fe_data_clean_11):
    # Rename column ('patient_health_questionnaire_9_little_interest_or_pleasure_in_doing_things', 'phq_0100') to 'little_interest_or_pleasure_freq_phq'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('patient_health_questionnaire_9_little_interest_or_pleasure_in_doing_things', 'phq_0100'): 'little_interest_or_pleasure_freq_phq'})
    # Rename column ('patient_health_questionnaire_9_feeling_down_depressed_or_hopeless', 'phq_0200') to 'feel_depressed_freq_phq'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('patient_health_questionnaire_9_feeling_down_depressed_or_hopeless', 'phq_0200'): 'feel_depressed_freq_phq'})
    # Rename column ('patient_health_questionnaire_9_trouble_falling_or_staying_asleep_or_sleeping_too_much', 'phq_0300') to 'trouble_sleeping_or_too_much_sleep_freq_phq'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('patient_health_questionnaire_9_trouble_falling_or_staying_asleep_or_sleeping_too_much', 'phq_0300'): 'trouble_sleeping_or_too_much_sleep_freq_phq'})
    # Rename column ('patient_health_questionnaire_9_feeling_tired_or_having_little_energy', 'phq_0400') to 'feel_no_energy_freq_phq'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('patient_health_questionnaire_9_feeling_tired_or_having_little_energy', 'phq_0400'): 'feel_no_energy_freq_phq'})
    # Rename column ('patient_health_questionnaire_9_poor_appetite_or_overeating', 'phq_0500') to 'poor_appetite_overeat_freq_phq'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('patient_health_questionnaire_9_poor_appetite_or_overeating', 'phq_0500'): 'poor_appetite_overeat_freq_phq'})
    # Rename column ('patient_health_questionnaire_9_feeling_bad_about_yourself', 'phq_0600') to 'feel_bad_abt_yourself_freq_phq'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('patient_health_questionnaire_9_feeling_bad_about_yourself', 'phq_0600'): 'feel_bad_abt_yourself_freq_phq'})
    # Rename column ('patient_health_questionnaire_9_trouble_concentrating', 'phq_0700') to 'trouble_focusing_freq_phq'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('patient_health_questionnaire_9_trouble_concentrating', 'phq_0700'): 'trouble_focusing_freq_phq'})
    # Rename column ('patient_health_questionnaire_9_moving_or_speaking_slowly', 'phq_0800') to 'slow_move_or_speak_freq_phq'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('patient_health_questionnaire_9_moving_or_speaking_slowly', 'phq_0800'): 'slow_move_or_speak_freq_phq'})
    # Rename column ('patient_health_questionnaire_9_thought_you_would_be_better_off_dead', 'phq_0900') to 'thought_you_would_be_better_dead_freq_phq'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('patient_health_questionnaire_9_thought_you_would_be_better_off_dead', 'phq_0900'): 'thought_you_would_be_better_dead_freq_phq'})
    # Rename column ('patient_health_questionnaire_9_total_score', 'phq_1000') to 'phq_total_score'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('patient_health_questionnaire_9_total_score', 'phq_1000'): 'phq_total_score'})
    # Rename column ('generalized_anxiety_disorder-7_questionnaire_feeling_nervous_anxious_or_on_edge', 'gad_0100') to 'feeling_anxious_freq_gad'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('generalized_anxiety_disorder-7_questionnaire_feeling_nervous_anxious_or_on_edge', 'gad_0100'): 'feeling_anxious_freq_gad'})
    # Rename column ('generalized_anxiety_disorder-7_questionnaire_not_being_able_to_stop_or_control_worrying', 'gad_0200') to 'not_able_to_control_worrying_freq_gad'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('generalized_anxiety_disorder-7_questionnaire_not_being_able_to_stop_or_control_worrying', 'gad_0200'): 'not_able_to_control_worrying_freq_gad'})
    # Rename column ('generalized_anxiety_disorder-7_questionnaire_worrying_too_much_about_different_things', 'gad_0300') to 'worry_too_much_diff_things_freq_gad'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('generalized_anxiety_disorder-7_questionnaire_worrying_too_much_about_different_things', 'gad_0300'): 'worry_too_much_diff_things_freq_gad'})
    # Rename column ('generalized_anxiety_disorder-7_questionnaire_trouble_relaxing', 'gad_0400') to 'trouble_relaxing_freq_gad'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('generalized_anxiety_disorder-7_questionnaire_trouble_relaxing', 'gad_0400'): 'trouble_relaxing_freq_gad'})
    # Rename column ('generalized_anxiety_disorder-7_questionnaire_being_so_restless_that_it_is_hard_to_sit_still', 'gad_0500') to 'cant_sit_still_freq_gad'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('generalized_anxiety_disorder-7_questionnaire_being_so_restless_that_it_is_hard_to_sit_still', 'gad_0500'): 'cant_sit_still_freq_gad'})
    # Rename column ('generalized_anxiety_disorder-7_questionnaire_becoming_easily_annoyed_or_irritable', 'gad_0600') to 'easily_annoyed_freq_gad'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('generalized_anxiety_disorder-7_questionnaire_becoming_easily_annoyed_or_irritable', 'gad_0600'): 'easily_annoyed_freq_gad'})
    # Rename column ('generalized_anxiety_disorder-7_questionnaire_feeling_afraid_as_if_something_awful_might_happen', 'gad_0700') to 'feel_as_if_awful_might_happen_freq_gad'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('generalized_anxiety_disorder-7_questionnaire_feeling_afraid_as_if_something_awful_might_happen', 'gad_0700'): 'feel_as_if_awful_might_happen_freq_gad'})
    # Rename column ('generalized_anxiety_disorder-7_questionnaire_total_score', 'gad_0800') to 'gad_total_score'
    fe_data_clean_11 = fe_data_clean_11.rename(columns={('generalized_anxiety_disorder-7_questionnaire_total_score', 'gad_0800'): 'gad_total_score'})
    return fe_data_clean_11

fe_data_clean_12 = clean_data(fe_data_clean_11.copy())
fe_data_clean_12.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [236]:
"""
Cell generated by Data Wrangler.
more renaming
"""
def clean_data(fe_data_clean_12):
    # Rename column ('fatigue_severity_scale_motivation_is_lower_when_fatigued', 'fss_0100') to 'lower_motivation_when_fati_fss'
    fe_data_clean_12 = fe_data_clean_12.rename(columns={('fatigue_severity_scale_motivation_is_lower_when_fatigued', 'fss_0100'): 'lower_motivation_when_fati_fss'})
    # Rename column ('fatigue_severity_scale_exercise_brings_on_fatigue', 'fss_0200') to 'exercise_brings_fati_fss'
    fe_data_clean_12 = fe_data_clean_12.rename(columns={('fatigue_severity_scale_exercise_brings_on_fatigue', 'fss_0200'): 'exercise_brings_fati_fss'})
    # Rename column ('fatigue_severity_scale_i_am_easily_fatigued', 'fss_0300') to 'i_am_easily_fati_fss'
    fe_data_clean_12 = fe_data_clean_12.rename(columns={('fatigue_severity_scale_i_am_easily_fatigued', 'fss_0300'): 'i_am_easily_fati_fss'})
    # Rename column ('fatigue_severity_scale_fatigue_interferes_with_physical_functioning', 'fss_0400') to 'fati_interferes_with_phys_function_fss'
    fe_data_clean_12 = fe_data_clean_12.rename(columns={('fatigue_severity_scale_fatigue_interferes_with_physical_functioning', 'fss_0400'): 'fati_interferes_with_phys_function_fss'})
    # Rename column ('fatigue_severity_scale_fatigue_causes_frequent_problems_for_me', 'fss_0500') to 'fati_causes_freq_probs_for_me_fss'
    fe_data_clean_12 = fe_data_clean_12.rename(columns={('fatigue_severity_scale_fatigue_causes_frequent_problems_for_me', 'fss_0500'): 'fati_causes_freq_probs_for_me_fss'})
    # Rename column ('fatigue_severity_scale_my_fatigue_prevents_sustained_physical_functioning', 'fss_0600') to 'fati_prevents_sustained_phys_func_fss'
    fe_data_clean_12 = fe_data_clean_12.rename(columns={('fatigue_severity_scale_my_fatigue_prevents_sustained_physical_functioning', 'fss_0600'): 'fati_prevents_sustained_phys_func_fss'})
    # Rename column ('fatigue_severity_scale_fatigue_interferes_with_carrying_out_certain_duties_and_responsibilities', 'fss_0700') to 'fati_interferes_with_responsibilities_fss'
    fe_data_clean_12 = fe_data_clean_12.rename(columns={('fatigue_severity_scale_fatigue_interferes_with_carrying_out_certain_duties_and_responsibilities', 'fss_0700'): 'fati_interferes_with_responsibilities_fss'})
    # Rename column ('fatigue_severity_scale_fatigue_is_among_my_three_most_disabling_symptoms', 'fss_0800') to 'fati_top_three_disabling_sympts_fss'
    fe_data_clean_12 = fe_data_clean_12.rename(columns={('fatigue_severity_scale_fatigue_is_among_my_three_most_disabling_symptoms', 'fss_0800'): 'fati_top_three_disabling_sympts_fss'})
    # Rename column ('fatigue_severity_scale_fatigue_interferes_with_my_work_family_or_social_life', 'fss_0900') to 'fati_interferes_with_work_fam_social_fss'
    fe_data_clean_12 = fe_data_clean_12.rename(columns={('fatigue_severity_scale_fatigue_interferes_with_my_work_family_or_social_life', 'fss_0900'): 'fati_interferes_with_work_fam_social_fss'})
    # Rename column ('fatigue_severity_scale_total_score', 'fss_1000') to 'fss_total_score'
    fe_data_clean_12 = fe_data_clean_12.rename(columns={('fatigue_severity_scale_total_score', 'fss_1000'): 'fss_total_score'})
    return fe_data_clean_12

fe_data_clean_13 = clean_data(fe_data_clean_12.copy())
fe_data_clean_13.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [237]:
"""
Cell generated by Data Wrangler.
i dont believe any of these will be useful and/or worth the effort to encode 
"""


def clean_data(fe_data_clean_13):
    # Drop columns: '('percentage_of_breakfast_among_all_food_intake_over_24_hours', 'diet_0300')', '('percentage_of_lunch_among_all_food_intake_over_24_hours', 'diet_0310')' and 6 other columns
    fe_data_clean_13 = fe_data_clean_13.drop(
        columns=[
            (
                "percentage_of_breakfast_among_all_food_intake_over_24_hours",
                "diet_0300",
            ),
            ("percentage_of_lunch_among_all_food_intake_over_24_hours", "diet_0310"),
            ("percentage_of_dinner_among_all_food_intake_over_24_hours", "diet_0320"),
            ("percentage_of_snack_1_among_all_food_intake_over_24_hours", "diet_0330"),
            ("percentage_of_snack_2_among_all_food_intake_over_24_hours", "diet_0350"),
            ("percentage_of_snack_3_among_all_food_intake_over_24_hours", "diet_0360"),
            ("percentage_of_snack_4_among_all_food_intake_over_24_hours", "diet_0370"),
            ("percentage_of_snack_5_among_all_food_intake_over_24_hours", "diet_0380"),
        ]
    )
    # Drop columns: '('usual_breakfast_time', 'diet_0800')', '('usually_no_breakfast', 'diet_0801')' and 14 other columns
    fe_data_clean_13 = fe_data_clean_13.drop(
        columns=[
            ("usual_breakfast_time", "diet_0800"),
            ("usually_no_breakfast", "diet_0801"),
            ("usual_lunch_time", "diet_0810"),
            ("usually_no_lunch", "diet_0811"),
            ("usual_dinner_time", "diet_0820"),
            ("usually_no_dinner", "diet_0821"),
            ("usual_additional_meal/snack_time1", "diet_0830"),
            ("usually_no_additional_meal/snack1", "diet_0831"),
            ("usual_additional_meal/snack_time2", "diet_0840"),
            ("usually_no_additional_meal/snack2", "diet_0841"),
            ("usual_additional_meal/snack_time3", "diet_0850"),
            ("usually_no_additional_meal/snack3", "diet_0851"),
            ("usual_additional_meal/snack_time4", "diet_0860"),
            ("usually_no_additional_meal/snack4", "diet_0861"),
            ("usual_additional_meal/snack_time5", "diet_0870"),
            ("usually_no_additional_meal/snack5", "diet_0871"),
        ]
    )
    return fe_data_clean_13


fe_data_clean_14 = clean_data(fe_data_clean_13.copy())
fe_data_clean_14.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [238]:
"""
Cell generated by Data Wrangler.
for eating_impact_alertness and perception of weight, the middle value is no change / normal weight 
and lower and higher are the ends. think about this later for encoding or swapping around variables values
"""
def clean_data(fe_data_clean_14):
    # Rename column ('eating_impact_on_alertness/wakefulness', 'diet_0400') to 'eating_impact_alertness'
    fe_data_clean_14 = fe_data_clean_14.rename(columns={('eating_impact_on_alertness/wakefulness', 'diet_0400'): 'eating_impact_alertness'})
    # Rename column ('feel_more_alert_if_skip_lunch', 'diet_0500') to 'feel_more_alert_if_skip_lunch'
    fe_data_clean_14 = fe_data_clean_14.rename(columns={('feel_more_alert_if_skip_lunch', 'diet_0500'): 'feel_more_alert_if_skip_lunch'})
    # Rename column ('sleep_less_soundly_if_skip_dinner', 'diet_0600') to 'sleep_less_sound_if_skip_dinner'
    fe_data_clean_14 = fe_data_clean_14.rename(columns={('sleep_less_soundly_if_skip_dinner', 'diet_0600'): 'sleep_less_sound_if_skip_dinner'})
    # Rename column ('self-perception_of_weight', 'diet_0700') to 'perception_of_weight'
    fe_data_clean_14 = fe_data_clean_14.rename(columns={('self-perception_of_weight', 'diet_0700'): 'perception_of_weight'})
    return fe_data_clean_14

fe_data_clean_15 = clean_data(fe_data_clean_14.copy())
fe_data_clean_15.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [239]:
## TODO: find a good way to encode these features : )

In [240]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean_15):
    # Rename column ('cigarette_smoking_never_smoker', 'never_cigarette_smoker') to 'never_smoked'
    fe_data_clean_15 = fe_data_clean_15.rename(columns={('cigarette_smoking_never_smoker', 'never_cigarette_smoker'): 'never_smoked'})
    # Rename column ('cigarette_smoking_former_smoker', 'former_cigarette_smoker') to 'former_smoker'
    fe_data_clean_15 = fe_data_clean_15.rename(columns={('cigarette_smoking_former_smoker', 'former_cigarette_smoker'): 'former_smoker'})
    # Drop column: '('smokeless_user_former_smoker', 'former_smokeless_user')'
    fe_data_clean_15 = fe_data_clean_15.drop(columns=[('smokeless_user_former_smoker', 'former_smokeless_user')])
    # Rename column ('cigarette_smoking_current_smoker', 'current_cigarette_smoker') to 'current_smoker'
    fe_data_clean_15 = fe_data_clean_15.rename(columns={('cigarette_smoking_current_smoker', 'current_cigarette_smoker'): 'current_smoker'})
    # Drop column: '('pregnancy_current', 'mdhx_1200')'
    fe_data_clean_15 = fe_data_clean_15.drop(columns=[('pregnancy_current', 'mdhx_1200')])
    # Drop column: '('smokeless_user_current_smoker', 'current_smokeless_user')'
    fe_data_clean_15 = fe_data_clean_15.drop(columns=[('smokeless_user_current_smoker', 'current_smokeless_user')])
    # Drop column: '('menopausal_status', 'mdhx_1300')'
    fe_data_clean_15 = fe_data_clean_15.drop(columns=[('menopausal_status', 'mdhx_1300')])
    return fe_data_clean_15

fe_data_clean_16 = clean_data(fe_data_clean_15.copy())
fe_data_clean_16.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [241]:
"""
Cell generated by Data Wrangler.
Essentially renaming all of the mdhx columns and removing the ones related to womens body functions becasue it 
doesnt seem to make sense 
"""


def clean_data(fe_data_clean_16):
    # Rename column ('oophorectomy_bilateral_self-reported', 'mdhx_1400') to 'oophorectomy_bilateral_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "oophorectomy_bilateral_self-reported",
                "mdhx_1400",
            ): "oophorectomy_bilateral_mdhx"
        }
    )
    # Rename column ('hypertension_self-reported', 'mdhx_5700') to 'hypertension_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={("hypertension_self-reported", "mdhx_5700"): "hypertension_mdhx"}
    )
    # Rename column ('congestive_heart_failure_self-reported', 'mdhx_5710') to 'congestive_heart_failure_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "congestive_heart_failure_self-reported",
                "mdhx_5710",
            ): "congestive_heart_failure_mdhx"
        }
    )
    # Rename column ('cardiovascular_problem_other_self-reported', 'mdhx_5720') to 'cardiovascular_problem_other_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "cardiovascular_problem_other_self-reported",
                "mdhx_5720",
            ): "cardiovascular_problem_other_mdhx"
        }
    )
    # Rename column ('asthma_self-reported', 'mdhx_5800') to 'asthma_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={("asthma_self-reported", "mdhx_5800"): "asthma_mdhx"}
    )
    # Rename column ('chronic_obstructive_pulmonary_disease_self-reported', 'mdhx_5810') to 'chronic_obstructive_pulmonary_disease_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "chronic_obstructive_pulmonary_disease_self-reported",
                "mdhx_5810",
            ): "chronic_obstructive_pulmonary_disease_mdhx"
        }
    )
    # Rename column ('pulmonary_problem_other_self-reported', 'mdhx_5820') to 'pulmonary_problem_other_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "pulmonary_problem_other_self-reported",
                "mdhx_5820",
            ): "pulmonary_problem_other_mdhx"
        }
    )
    # Rename column ('allergies_or_sinus_problems_self-reported', 'mdhx_5900') to 'allergies_or_sinus_problems_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "allergies_or_sinus_problems_self-reported",
                "mdhx_5900",
            ): "allergies_or_sinus_problems_mdhx"
        }
    )
    # Rename column ('tonsillectomy_or_adenoidectomy_self-reported', 'mdhx_5910') to 'tonsillectomy_or_adenoidectomy_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "tonsillectomy_or_adenoidectomy_self-reported",
                "mdhx_5910",
            ): "tonsillectomy_or_adenoidectomy_mdhx"
        }
    )
    # Rename column ('nasal_jaw_or_apnea_surgery_self-reported', 'mdhx_5920') to 'nasal_jaw_or_apnea_surgery_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "nasal_jaw_or_apnea_surgery_self-reported",
                "mdhx_5920",
            ): "nasal_jaw_or_apnea_surgery_mdhx"
        }
    )
    # Rename column ('ear_nose_and_throat_problem_or_surgery_other_self-reported', 'mdhx_5950') to 'ear_nose_and_throat_problem_or_surgery_other_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "ear_nose_and_throat_problem_or_surgery_other_self-reported",
                "mdhx_5950",
            ): "ear_nose_and_throat_problem_or_surgery_other_mdhx"
        }
    )
    # Rename column ('dental_problems_self-reported', 'mdhx_6000') to 'dental_problems_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={("dental_problems_self-reported", "mdhx_6000"): "dental_problems_mdhx"}
    )
    # Drop column: '('dentures_removed_while_sleeping_self-reported', 'mdhx_6030')'
    fe_data_clean_16 = fe_data_clean_16.drop(
        columns=[("dentures_removed_while_sleeping_self-reported", "mdhx_6030")]
    )
    # Rename column ('gastrointestinal_problem_or_surgery_self-reported', 'mdhx_6100') to 'gastrointestinal_problem_or_surgery_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "gastrointestinal_problem_or_surgery_self-reported",
                "mdhx_6100",
            ): "gastrointestinal_problem_or_surgery_mdhx"
        }
    )
    # Rename column ('neurologic_problem_self-reported', 'mdhx_6200') to 'neurologic_problem_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            ("neurologic_problem_self-reported", "mdhx_6200"): "neurologic_problem_mdhx"
        }
    )
    # Rename column ('hypercholesterolemia_self-reported', 'mdhx_6300') to 'hypercholesterolemia_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "hypercholesterolemia_self-reported",
                "mdhx_6300",
            ): "hypercholesterolemia_mdhx"
        }
    )
    # Rename column ('type_2_diabetes_self-reported', 'mdhx_6310') to 'type_2_diabetes_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={("type_2_diabetes_self-reported", "mdhx_6310"): "type_2_diabetes_mdhx"}
    )
    # Rename column ('endocrine_or_metabolic_problem_self-reported', 'mdhx_6320') to 'endocrine_or_metabolic_problem_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "endocrine_or_metabolic_problem_self-reported",
                "mdhx_6320",
            ): "endocrine_or_metabolic_problem_mdhx"
        }
    )
    # Rename column ('urologic_or_kidney_problem_self-reported', 'mdhx_6400') to 'urologic_or_kidney_problem_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "urologic_or_kidney_problem_self-reported",
                "mdhx_6400",
            ): "urologic_or_kidney_problem_mdhx"
        }
    )
    # Rename column ('pain_or_fatigue_self-reported', 'mdhx_6500') to 'pain_or_fatigue_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={("pain_or_fatigue_self-reported", "mdhx_6500"): "pain_or_fatigue_mdhx"}
    )
    # Rename column ('psychiatric_or_mental_health_problem_self-reported', 'mdhx_6600') to 'psychiatric_or_mental_health_problem_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "psychiatric_or_mental_health_problem_self-reported",
                "mdhx_6600",
            ): "psychiatric_or_mental_health_problem_mdhx"
        }
    )
    # Rename column ('medical_problem_or_surgery_other_self-reported', 'mdhx_6700') to 'medical_problem_or_surgery_other_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "medical_problem_or_surgery_other_self-reported",
                "mdhx_6700",
            ): "medical_problem_or_surgery_other_mdhx"
        }
    )
    # Rename column ('genetic_testing_self-reported', 'mdhx_6900') to 'genetic_testing_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={("genetic_testing_self-reported", "mdhx_6900"): "genetic_testing_mdhx"}
    )
    # Drop column: '('genetic_testing_source_self-reported', 'mdhx_6910')'
    fe_data_clean_16 = fe_data_clean_16.drop(
        columns=[("genetic_testing_source_self-reported", "mdhx_6910")]
    )
    # Rename column ('family_history_of_insomnia', 'famhx_0100') to 'family_history_of_insomnia_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "family_history_of_insomnia",
                "famhx_0100",
            ): "family_history_of_insomnia_mdhx"
        }
    )
    # Rename column ('family_history_of_sleep_apnea', 'famhx_0200') to 'family_history_of_sleep_apnea_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "family_history_of_sleep_apnea",
                "famhx_0200",
            ): "family_history_of_sleep_apnea_mdhx"
        }
    )
    # Rename column ('family_history_of_narcolepsy', 'famhx_0300') to 'family_history_of_narcolepsy_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "family_history_of_narcolepsy",
                "famhx_0300",
            ): "family_history_of_narcolepsy_mdhx"
        }
    )
    # Rename column ('family_history_of_restless_leg_syndrome', 'famhx_0400') to 'family_history_of_restless_leg_syndrome_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "family_history_of_restless_leg_syndrome",
                "famhx_0400",
            ): "family_history_of_restless_leg_syndrome_mdhx"
        }
    )
    # Rename column ('family_history_of_other_sleep_disorder', 'famhx_0500') to 'family_history_of_other_sleep_disorder_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "family_history_of_other_sleep_disorder",
                "famhx_0500",
            ): "family_history_of_other_sleep_disorder_mdhx"
        }
    )
    # Rename column ('family_history_of_sleepwalking', 'famhx_0600') to 'family_history_of_sleepwalking_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "family_history_of_sleepwalking",
                "famhx_0600",
            ): "family_history_of_sleepwalking_mdhx"
        }
    )
    # Rename column ('family_history_of_fibromyalgia_or_chronic_fatigue', 'famhx_0700') to 'family_history_of_fibromyalgia_or_chronic_fatigue_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "family_history_of_fibromyalgia_or_chronic_fatigue",
                "famhx_0700",
            ): "family_history_of_fibromyalgia_or_chronic_fatigue_mdhx"
        }
    )
    # Rename column ('family_history_of_depression', 'famhx_0800') to 'family_history_of_depression_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "family_history_of_depression",
                "famhx_0800",
            ): "family_history_of_depression_mdhx"
        }
    )
    # Rename column ('family_history_of_anxiety', 'famhx_0900') to 'family_history_of_anxiety_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "family_history_of_anxiety",
                "famhx_0900",
            ): "family_history_of_anxiety_mdhx"
        }
    )
    # Rename column ('family_history_of_other_psychiatric_illness', 'famhx_1000') to 'family_history_of_other_psychiatric_illness_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "family_history_of_other_psychiatric_illness",
                "famhx_1000",
            ): "family_history_of_other_psychiatric_illness_mdhx"
        }
    )
    # Rename column ('family_history_of_psychiatric_treatment', 'famhx_1100') to 'family_history_of_psychiatric_treatment_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "family_history_of_psychiatric_treatment",
                "famhx_1100",
            ): "family_history_of_psychiatric_treatment_mdhx"
        }
    )
    # Rename column ('family_history_of_death_during_sleep', 'famhx_1200') to 'family_history_of_death_during_sleep_mdhx'
    fe_data_clean_16 = fe_data_clean_16.rename(
        columns={
            (
                "family_history_of_death_during_sleep",
                "famhx_1200",
            ): "family_history_of_death_during_sleep_mdhx"
        }
    )
    return fe_data_clean_16


fe_data_clean_17 = clean_data(fe_data_clean_16.copy())
fe_data_clean_17.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [242]:
"""
Cell generated by Data Wrangler.
removing or renaming features; removed ones all mostly had extremely high counts of 
missing values which made it practically  impossible to work with
"""
def clean_data(fe_data_clean_17):
    # Rename column ('number_of_full_siblings_from_the_same_birth_parents', 'famhx_1300') to 'num_full_siblings'
    fe_data_clean_17 = fe_data_clean_17.rename(columns={('number_of_full_siblings_from_the_same_birth_parents', 'famhx_1300'): 'num_full_siblings'})
    # Rename column ('hypnogogic_hallucinations_days_per_week', 'map_1100') to 'num_hypnogogic_hallus_days_per_week'
    fe_data_clean_17 = fe_data_clean_17.rename(columns={('hypnogogic_hallucinations_days_per_week', 'map_1100'): 'num_hypnogogic_hallus_days_per_week'})
    # Drop column: '('hypnogogic_hallucinations_number_of_times', 'map_1110')'
    fe_data_clean_17 = fe_data_clean_17.drop(columns=[('hypnogogic_hallucinations_number_of_times', 'map_1110')])
    # Drop column: '('hypnogogic_hallucinations_time_frame', 'map_1120')'
    fe_data_clean_17 = fe_data_clean_17.drop(columns=[('hypnogogic_hallucinations_time_frame', 'map_1120')])
    # Drop column: '('hypnogogic_hallucinations_age_of_the_first_episode', 'map_1130')'
    fe_data_clean_17 = fe_data_clean_17.drop(columns=[('hypnogogic_hallucinations_age_of_the_first_episode', 'map_1130')])
    # Drop column: '('hypnogogic_hallucinations_age_of_the_first_episode_dont_know', 'map_1131')'
    fe_data_clean_17 = fe_data_clean_17.drop(columns=[('hypnogogic_hallucinations_age_of_the_first_episode_dont_know', 'map_1131')])
    # Drop columns: '('frequency_of_leg_twitch/kick_time_frame', 'par_0110')', '('frequency_of_leg_twitch/kick_never_or_dont_know', 'par_0101')', '('frequency_of_leg_twitch/kick_number_of_times', 'par_0100')'
    fe_data_clean_17 = fe_data_clean_17.drop(columns=[('frequency_of_leg_twitch/kick_time_frame', 'par_0110'), ('frequency_of_leg_twitch/kick_never_or_dont_know', 'par_0101'), ('frequency_of_leg_twitch/kick_number_of_times', 'par_0100')])
    # Drop column: '('frequency_of_sleepwalk_number_of_times', 'par_0200')'
    fe_data_clean_17 = fe_data_clean_17.drop(columns=[('frequency_of_sleepwalk_number_of_times', 'par_0200')])
    # Drop columns: '('frequency_of_sleepwalk_never_or_dont_know', 'par_0201')', '('frequency_of_sleepwalk_time_frame', 'par_0210')', '('sleepwalk_age_of_the_first_episode', 'par_0230')'
    fe_data_clean_17 = fe_data_clean_17.drop(columns=[('frequency_of_sleepwalk_never_or_dont_know', 'par_0201'), ('frequency_of_sleepwalk_time_frame', 'par_0210'), ('sleepwalk_age_of_the_first_episode', 'par_0230')])
    # Drop columns: '('frequency_of_acting_out_dreams_times', 'par_0500')', '('frequency_of_acting_out_dreams_time_frame', 'par_0510')' and 6 other columns
    fe_data_clean_17 = fe_data_clean_17.drop(columns=[('frequency_of_acting_out_dreams_times', 'par_0500'), ('frequency_of_acting_out_dreams_time_frame', 'par_0510'), ('frequency_of_acting_out_dreams_never_or_dont_know', 'par_0501'), ('acting_out_dreams_age_of_the_first_episode', 'par_0530'), ('frequency_of_violent_behavior_during_sleep_times', 'par_0600'), ('frequency_of_violent_behavior_during_sleep_never_or_dont_know', 'par_0601'), ('frequency_of_violent_behavior_during_sleep_time_frame', 'par_0610'), ('violent_behavior_during_sleep_age_of_the_first_episode', 'par_0630')])
    # Rename column ('frequency_of_teeth_grinding', 'par_0400') to 'freq_teeth_grinding'
    fe_data_clean_17 = fe_data_clean_17.rename(columns={('frequency_of_teeth_grinding', 'par_0400'): 'freq_teeth_grinding'})
    return fe_data_clean_17

fe_data_clean_18 = clean_data(fe_data_clean_17.copy())
fe_data_clean_18.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [243]:
"""
encoding nightmare info
probably best to put into buckets later but that will be handled

"""

fe_data_clean_18 = fe_data_clean_18.rename(
    columns={
        ("frequency_of_nightmares_times", "par_0700"): "num_nightmares",
        ('frequency_of_nightmares_never_or_dont_know', 'par_0701'
         ): "nightmares_never_or_dont_know",
        ("frequency_of_nightmares_time_frame", "par_0710"): "nightmares_time_frame",
    }
)

nightmare_time_frame_mapping = {
    0: "per week",
    1: "per month",
    2: "per year"
}

fe_data_clean_18["nightmares_time_frame"] = fe_data_clean_18["nightmares_time_frame"].map(nightmare_time_frame_mapping)

fe_data_clean_18["nightmare_string"] = fe_data_clean_18["num_nightmares"].astype(str) + " " + fe_data_clean_18["nightmares_time_frame"]
fe_data_clean_18 = fe_data_clean_18.astype({'num_nightmares': 'string'})
fe_data_clean_18["num_nightmares"] = fe_data_clean_18["nightmare_string"]

fe_data_clean_18 = fe_data_clean_18.drop(columns=["nightmares_time_frame", "nightmare_string"])

fe_data_clean_18 = fe_data_clean_18.rename(columns={"num_nightmares": "nightmares_freq"})

fe_data_clean_18["nightmares_freq"] = np.where(
    fe_data_clean_18["nightmares_never_or_dont_know"].fillna(False),
    "never or don't know",
    fe_data_clean_18["nightmares_freq"]
)

fe_data_clean_18 = fe_data_clean_18.drop(columns=["nightmares_never_or_dont_know"])

fe_data_clean_18.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [244]:
"""
Cell generated by Data Wrangler.
rls columns too broad and unrelated to sleep apnea to be worth including all of them so just kept the one hot encoded probability and 
severity for those who do have; will move that into others soon
"""
def clean_data(fe_data_clean_18):
    # Drop column: '('seizures_during_sleep', 'par_0800')'
    fe_data_clean_18 = fe_data_clean_18.drop(columns=[('seizures_during_sleep', 'par_0800')])
    # Drop columns: '('did_it_end_with_same_pregnancy', 'rls_0910')', '('did_it_begin_with_pregnancy', 'rls_0900')' and 13 other columns
    fe_data_clean_18 = fe_data_clean_18.drop(columns=[('did_it_end_with_same_pregnancy', 'rls_0910'), ('did_it_begin_with_pregnancy', 'rls_0900'), ('unpleasant_feelings_in_legs_age_of_the_first_episode_(present_and_past)', 'rls_0800'), ('unpleasant_sensation_always_due_to_muscle_cramp_present', 'rls_0300'), ('how_often_did_sensations_occur_past', 'rls_0710'), ('how_often_do_sensations_occur_present', 'rls_0700'), ('how_distressing_were_sensations_past', 'rls_0610'), ('how_distressing_are_sensations_present', 'rls_0600'), ('sensations_were_worse_in_evening_past', 'rls_0510'), ('sensations_worse_in_evening_present', 'rls_0500'), ('unpleasant_sensation_was_always_due_to_muscle_cramp_past', 'rls_0310'), ('improve_with_movement_present', 'rls_0400'), ('improved_with_movement_past', 'rls_0410'), ('urge_to_move_legs', 'rls_0200'), ('unpleasant_feelings_in_legs', 'rls_0100')])
    # Rename column "('restless_legs_syndrome_(rls)_current_probability', 'rls_probability')_Likely" to 'rls_likely'
    fe_data_clean_18 = fe_data_clean_18.rename(columns={"('restless_legs_syndrome_(rls)_current_probability', 'rls_probability')_Likely": 'rls_likely'})
    # Rename column "('restless_legs_syndrome_(rls)_current_probability', 'rls_probability')_Possible" to 'rls_possible_curr'
    fe_data_clean_18 = fe_data_clean_18.rename(columns={"('restless_legs_syndrome_(rls)_current_probability', 'rls_probability')_Possible": 'rls_possible_curr'})
    # Rename column 'rls_likely' to 'rls_likely_curr'
    fe_data_clean_18 = fe_data_clean_18.rename(columns={'rls_likely': 'rls_likely_curr'})
    # Rename column "('restless_legs_syndrome_(rls)_current_probability', 'rls_probability')_Unlikely" to 'rls_unlikely_curr'
    fe_data_clean_18 = fe_data_clean_18.rename(columns={"('restless_legs_syndrome_(rls)_current_probability', 'rls_probability')_Unlikely": 'rls_unlikely_curr'})
    # Rename column "('restless_legs_syndrome_(rls)_current_probability', 'rls_probability')_Unlikely (possibly in past)" to 'rls_unlikely_curr_probably_past'
    fe_data_clean_18 = fe_data_clean_18.rename(columns={"('restless_legs_syndrome_(rls)_current_probability', 'rls_probability')_Unlikely (possibly in past)": 'rls_unlikely_curr_probably_past'})
    # Rename column ('restless_legs_syndrome_(rls)_current_severity', 'rls_severity') to 'rls_severity_current'
    fe_data_clean_18 = fe_data_clean_18.rename(columns={('restless_legs_syndrome_(rls)_current_severity', 'rls_severity'): 'rls_severity_current'})
    return fe_data_clean_18

fe_data_clean_19 = clean_data(fe_data_clean_18.copy())
fe_data_clean_19.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [245]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean_19):
    # Rename column ('last_use_tv_or_computer_before_bed', 'bthbts_0300') to 'screen_before_bed_hrs'
    fe_data_clean_19 = fe_data_clean_19.rename(columns={('last_use_tv_or_computer_before_bed', 'bthbts_0300'): 'screen_before_bed_hrs'})
    # Rename column ('time_in_bed_non_sch_non_work_nights', 'sched_1900') to 'bedtime_no_sw'
    fe_data_clean_19 = fe_data_clean_19.rename(columns={('time_in_bed_non_sch_non_work_nights', 'sched_1900'): 'bedtime_no_sw'})
    # Rename column ('time_in_bed_non_sch_non_work_nights_varies', 'sched_1901') to 'bedtime_no_sw_varies'
    fe_data_clean_19 = fe_data_clean_19.rename(columns={('time_in_bed_non_sch_non_work_nights_varies', 'sched_1901'): 'bedtime_no_sw_varies'})
    # Rename column ('time_out_bed_non_sch_non_work_nights', 'sched_2000') to 'wakeup_non_sw'
    fe_data_clean_19 = fe_data_clean_19.rename(columns={('time_out_bed_non_sch_non_work_nights', 'sched_2000'): 'wakeup_non_sw'})
    # Rename column ('time_out_bed_non_sch_non_work_nights_varies', 'sched_2001') to 'wakeup_no_sw_varies'
    fe_data_clean_19 = fe_data_clean_19.rename(columns={('time_out_bed_non_sch_non_work_nights_varies', 'sched_2001'): 'wakeup_no_sw_varies'})
    # Rename column 'wakeup_non_sw' to 'wakeup_no_sw'
    fe_data_clean_19 = fe_data_clean_19.rename(columns={'wakeup_non_sw': 'wakeup_no_sw'})
    # Rename column ('amount_of_sleep_needed_to_feel_fully_rested_never_rested', 'sched_4201') to 'never_feel_rested'
    fe_data_clean_19 = fe_data_clean_19.rename(columns={('amount_of_sleep_needed_to_feel_fully_rested_never_rested', 'sched_4201'): 'never_feel_rested'})
    return fe_data_clean_19

fe_data_clean_20 = clean_data(fe_data_clean_19.copy())
fe_data_clean_20.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [246]:
"""
combining nap time features
"""

nap_freq_period_mapping = {
    0: "per week",
    1: "per month",
    2: "per year"
}

fe_data_clean_20 = fe_data_clean_20.rename(
    columns={
        ("self-reported_frequency_of_napping", "soclhx_0100"): "nap_num",
        ("self-reported_frequency_of_napping", "soclhx_0110"): "nap_freq_period",
    }
)

fe_data_clean_20["nap_freq_period"] = fe_data_clean_20["nap_freq_period"].map(nap_freq_period_mapping)

fe_data_clean_20["nap_freq"] = fe_data_clean_20["nap_num"].astype(str) + " " + fe_data_clean_20["nap_freq_period"]

fe_data_clean_20 = fe_data_clean_20.astype({'nap_num': 'string'})

fe_data_clean_20["nap_num"] = fe_data_clean_20["nap_freq"]

fe_data_clean_20 = fe_data_clean_20.drop(columns=["nap_freq_period", "nap_freq"])

fe_data_clean_20.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [247]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean_20):
    # Rename column ('feeling_refreshed_after_nap', 'soclhx_0300') to 'feel_refreshed_after_nap'
    fe_data_clean_20 = fe_data_clean_20.rename(columns={('feeling_refreshed_after_nap', 'soclhx_0300'): 'feel_refreshed_after_nap'})
    # Rename column ('easily_awakened_after_nap', 'soclhx_0400') to 'easily_awake_after_nap'
    fe_data_clean_20 = fe_data_clean_20.rename(columns={('easily_awakened_after_nap', 'soclhx_0400'): 'easily_awake_after_nap'})
    # Rename column ('alcohol_consumption_as_sleep_aid', 'soclhx_0800') to 'alcohol_as_sleep_aid'
    fe_data_clean_20 = fe_data_clean_20.rename(columns={('alcohol_consumption_as_sleep_aid', 'soclhx_0800'): 'alcohol_as_sleep_aid'})
    # Rename column ('feeling_that_sleep_is_not_sound', 'isq_0400') to 'feel_sleep_not_sound_isq'
    fe_data_clean_20 = fe_data_clean_20.rename(columns={('feeling_that_sleep_is_not_sound', 'isq_0400'): 'feel_sleep_not_sound_isq'})
    # Drop columns: '('feeling_that_sleep_is_not_sound_number', 'isq_0410')', '('feeling_that_sleep_is_not_sound_time_frame', 'isq_0420')'
    fe_data_clean_20 = fe_data_clean_20.drop(columns=[('feeling_that_sleep_is_not_sound_number', 'isq_0410'), ('feeling_that_sleep_is_not_sound_time_frame', 'isq_0420')])
    # Rename column ('feeling_that_sleep_is_unrefreshing', 'isq_0500') to 'feel_sleep_unrefreshing_isq'
    fe_data_clean_20 = fe_data_clean_20.rename(columns={('feeling_that_sleep_is_unrefreshing', 'isq_0500'): 'feel_sleep_unrefreshing_isq'})
    # Drop columns: '('feeling_that_sleep_is_unrefreshing_time_frame', 'isq_0520')', '('feeling_that_sleep_is_unrefreshing__number', 'isq_0510')'
    fe_data_clean_20 = fe_data_clean_20.drop(columns=[('feeling_that_sleep_is_unrefreshing_time_frame', 'isq_0520'), ('feeling_that_sleep_is_unrefreshing__number', 'isq_0510')])
    # Rename column ('how_much_does_your_sleep_bother_you', 'isq_0600') to 'how_much_does_your_sleep_bother_you_isq'
    fe_data_clean_20 = fe_data_clean_20.rename(columns={('how_much_does_your_sleep_bother_you', 'isq_0600'): 'how_much_does_your_sleep_bother_you_isq'})
    # Rename column ('frequency_of_eat/drink_in_sleep_number_of_times', 'par_0300') to 'num_times_eat_drink_dur_sleep'
    fe_data_clean_20 = fe_data_clean_20.rename(columns={('frequency_of_eat/drink_in_sleep_number_of_times', 'par_0300'): 'num_times_eat_drink_dur_sleep'})
    # Rename column ('frequency_of_eat/drink_in_sleep_never_or_dont_know', 'par_0301') to 'num_times_eat_drink_dur_sleep_dont_know'
    fe_data_clean_20 = fe_data_clean_20.rename(columns={('frequency_of_eat/drink_in_sleep_never_or_dont_know', 'par_0301'): 'num_times_eat_drink_dur_sleep_dont_know'})
    # Rename column ('frequency_of_eat/drink_in_sleep_time_frame', 'par_0310') to 'eat_drink_sleep_time_frame'
    fe_data_clean_20 = fe_data_clean_20.rename(columns={('frequency_of_eat/drink_in_sleep_time_frame', 'par_0310'): 'eat_drink_sleep_time_frame'})
    # Rename column ('rarely_or_never_nap', 'soclhx_0101') to 'rarely_or_never_nap'
    fe_data_clean_20 = fe_data_clean_20.rename(columns={('rarely_or_never_nap', 'soclhx_0101'): 'rarely_or_never_nap'})
    return fe_data_clean_20

fe_data_clean_21 = clean_data(fe_data_clean_20.copy())
fe_data_clean_21.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [248]:
freq_period_mapping = {0: "per week", 1: "per month", 2: "per year"}

fe_data_clean_21["eat_drink_sleep_time_frame"] = fe_data_clean_21[
    "eat_drink_sleep_time_frame"
].map(freq_period_mapping)

fe_data_clean_21["eat_drink_sleep_freq"] = (
    fe_data_clean_21["num_times_eat_drink_dur_sleep"].astype(str)
    + " "
    + fe_data_clean_21["eat_drink_sleep_time_frame"]
)

fe_data_clean_21['num_times_eat_drink_dur_sleep'] = fe_data_clean_21['eat_drink_sleep_freq']
fe_data_clean_21 = fe_data_clean_21.drop(columns=["eat_drink_sleep_time_frame", "eat_drink_sleep_freq"])

fe_data_clean_21['num_times_eat_drink_dur_sleep'] = np.where(
    fe_data_clean_21['num_times_eat_drink_dur_sleep_dont_know'].fillna(False),
    "never or don't know",
    fe_data_clean_21['num_times_eat_drink_dur_sleep']
)

fe_data_clean_21 = fe_data_clean_21.drop(columns=['num_times_eat_drink_dur_sleep_dont_know'])

fe_data_clean_21.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [249]:
""" 
adding rarely_or_never_nap to nap col
"""

fe_data_clean_21['nap_num'] = np.where(
    fe_data_clean_21['rarely_or_never_nap'].fillna(True),
    "rarely or never",
    fe_data_clean_21['nap_num']
)

fe_data_clean_21 = fe_data_clean_21.drop(columns=['rarely_or_never_nap'])

fe_data_clean_21.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [250]:
"""
Cell generated by Data Wrangler.
notebook started tweaking so reset in middle of renaming stuff
"""
def clean_data(fe_data_clean_21):
    # Rename column ('time_out_bed_sch_work_nights', 'sched_9900') to 'wakeup_sw'
    fe_data_clean_21 = fe_data_clean_21.rename(columns={('time_out_bed_sch_work_nights', 'sched_9900'): 'wakeup_sw'})
    # Rename column ('time_out_bed_sch_work_nights_varies', 'sched_9901') to 'wakeup_sw_varies'
    fe_data_clean_21 = fe_data_clean_21.rename(columns={('time_out_bed_sch_work_nights_varies', 'sched_9901'): 'wakeup_sw_varies'})
    # Rename column ('time_in_bed_sch_work_nights_varies', 'sched_0901') to 'bedtime_sw_varies'
    fe_data_clean_21 = fe_data_clean_21.rename(columns={('time_in_bed_sch_work_nights_varies', 'sched_0901'): 'bedtime_sw_varies'})
    # Rename column ('time_in_bed_sch_work_nights', 'sched_0900') to 'bedtime_sw'
    fe_data_clean_21 = fe_data_clean_21.rename(columns={('time_in_bed_sch_work_nights', 'sched_0900'): 'bedtime_sw'})
    # Rename column ('latency_sch_work_nights', 'sched_2200') to 'latency_sw'
    fe_data_clean_21 = fe_data_clean_21.rename(columns={('latency_sch_work_nights', 'sched_2200'): 'latency_sw'})
    # Rename column ('latency_non_sch_non_work_nights', 'sched_3700') to 'latency_no_sw'
    fe_data_clean_21 = fe_data_clean_21.rename(columns={('latency_non_sch_non_work_nights', 'sched_3700'): 'latency_no_sw'})
    # Rename column ('total_slp_duration_sch_work_nights', 'sched_2300') to 'slp_dur_sw'
    fe_data_clean_21 = fe_data_clean_21.rename(columns={('total_slp_duration_sch_work_nights', 'sched_2300'): 'slp_dur_sw'})
    # Rename column 'slp_dur_sw' to 'total_slp_duration_sw'
    fe_data_clean_21 = fe_data_clean_21.rename(columns={'slp_dur_sw': 'total_slp_duration_sw'})
    # Rename column ('total_slp_duration_non_sch_non_work_nights', 'sched_3800') to 'total_slp_duration_no_sw'
    fe_data_clean_21 = fe_data_clean_21.rename(columns={('total_slp_duration_non_sch_non_work_nights', 'sched_3800'): 'total_slp_duration_no_sw'})
    # Rename column ('slp_quality_sch_work_nights', 'sched_2600') to 'slp_quality_sw'
    fe_data_clean_21 = fe_data_clean_21.rename(columns={('slp_quality_sch_work_nights', 'sched_2600'): 'slp_quality_sw'})
    return fe_data_clean_21

fe_data_clean_22 = clean_data(fe_data_clean_21.copy())
fe_data_clean_22.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [251]:
"""
Cell generated by Data Wrangler.
Dropped narcolepsy columns becasue those are related to narcolepsy and not sleep apnea put simply
"""
def clean_data(fe_data_clean_22):
    # Rename column ('slp_quality_non_sch_non_work_nights', 'sched_4100') to 'slp_quality_no_sw'
    fe_data_clean_22 = fe_data_clean_22.rename(columns={('slp_quality_non_sch_non_work_nights', 'sched_4100'): 'slp_quality_no_sw'})
    # Rename column ('amt_slp_fully_rested', 'sched_4200') to 'amt_slp_fully_rested'
    fe_data_clean_22 = fe_data_clean_22.rename(columns={('amt_slp_fully_rested', 'sched_4200'): 'amt_slp_fully_rested'})
    # Rename column ('usual_nap_duration', 'soclhx_0200') to 'usual_nap_duration'
    fe_data_clean_22 = fe_data_clean_22.rename(columns={('usual_nap_duration', 'soclhx_0200'): 'usual_nap_duration'})
    # Drop columns: '('feel_paralyzed_(cataplexy)_time_frame', 'map_1030')', '('feel_paralyzed_(cataplexy)_number_of_times', 'map_1020')'
    fe_data_clean_22 = fe_data_clean_22.drop(columns=[('feel_paralyzed_(cataplexy)_time_frame', 'map_1030'), ('feel_paralyzed_(cataplexy)_number_of_times', 'map_1020')])
    # Drop columns: '('feel_paralyzed_(cataplexy)_when', 'map_1010')', '('feel_paralyzed_(cataplexy)_age_of_the_first_episode', 'map_1040')', '('feel_paralyzed_(cataplexy)_age_of_the_first_episode_dont_know', 'map_1041')'
    fe_data_clean_22 = fe_data_clean_22.drop(columns=[('feel_paralyzed_(cataplexy)_when', 'map_1010'), ('feel_paralyzed_(cataplexy)_age_of_the_first_episode', 'map_1040'), ('feel_paralyzed_(cataplexy)_age_of_the_first_episode_dont_know', 'map_1041')])
    # Rename column ('feel_paralyzed_(cataplexy)_days_per_week', 'map_1000') to 'cataplexy_days_per_week'
    fe_data_clean_22 = fe_data_clean_22.rename(columns={('feel_paralyzed_(cataplexy)_days_per_week', 'map_1000'): 'cataplexy_days_per_week'})
    # Rename column ('map_index_4_narcolepsy_like_symptoms_score', 'index_4') to 'map_index_4_narcolepsy_like_symptoms_score'
    fe_data_clean_22 = fe_data_clean_22.rename(columns={('map_index_4_narcolepsy_like_symptoms_score', 'index_4'): 'map_index_4_narcolepsy_like_symptoms_score'})
    # Rename column ('currently_being_treated_for_narcolepsy', 'narc_0050') to 'current_treated_for_narcolepsy'
    fe_data_clean_22 = fe_data_clean_22.rename(columns={('currently_being_treated_for_narcolepsy', 'narc_0050'): 'current_treated_for_narcolepsy'})
    # Drop columns: '('frequency_of_muscle_weakness_when_tell_or_hear_joke_before_treatment', 'narc_0110')', '('sagging_or_dropping_of_jaw', 'narc_0600')' and 10 other columns
    fe_data_clean_22 = fe_data_clean_22.drop(columns=[('frequency_of_muscle_weakness_when_tell_or_hear_joke_before_treatment', 'narc_0110'), ('sagging_or_dropping_of_jaw', 'narc_0600'), ('abrupt_dropping_of_head_and/or_shoulders', 'narc_0700'), ('frequency_of_muscle_weakness_when_making_verbal_response_in_playful_context_before_treatment', 'narc_0510'), ('frequency_of_muscle_weakness_when_making_verbal_response_in_playful_context_current', 'narc_0500'), ('frequency_of_muscle_weakness_when_stressed_before_treatment', 'narc_0410'), ('frequency_of_muscle_weakness_when_stressed_current', 'narc_0400'), ('frequency_of_muscle_weakness_when_angry_before_treatment', 'narc_0310'), ('frequency_of_muscle_weakness_when_angry_current', 'narc_0300'), ('frequency_of_muscle_weakness_when_laugh_before_treatment', 'narc_0210'), ('frequency_of_muscle_weakness_when_laugh_current', 'narc_0200'), ('frequency_of_muscle_weakness_when_tell_or_hear_joke_present', 'narc_0100')])
    # Drop columns: '('fallen_to_ground_unable_to_move', 'narc_1000')', '('slurring_of_speech', 'narc_0900')', '('weakness_in_arms', 'narc_0800')'
    fe_data_clean_22 = fe_data_clean_22.drop(columns=[('fallen_to_ground_unable_to_move', 'narc_1000'), ('slurring_of_speech', 'narc_0900'), ('weakness_in_arms', 'narc_0800')])
    # Drop columns: '('can_you_see_during_a_typical_episode', 'narc_1300')', '('can_you_hear_during_a_typical_episode', 'narc_1200')' and 8 other columns
    fe_data_clean_22 = fe_data_clean_22.drop(columns=[('can_you_see_during_a_typical_episode', 'narc_1300'), ('can_you_hear_during_a_typical_episode', 'narc_1200'), ('duration_of_the_muscle_weakness', 'narc_1100'), ('do_you_fall_asleep_during_a_typical_episode', 'narc_1400'), ('do_you_have_time_to_sit_or_break_your_fall_during_a_typical_episode', 'narc_1500'), ('muscle_weakness_number_of_episode', 'narc_1600'), ('muscle_weakness_time_frame', 'narc_1610'), ('muscle_weakness_last_experience', 'narc_1650'), ('muscle_weakness_age_of_the_first_episode', 'narc_1700'), ('muscle_weakness_age_of_the_first_episode_dont_know', 'narc_1701')])
    return fe_data_clean_22

fe_data_clean_23 = clean_data(fe_data_clean_22.copy())
fe_data_clean_23.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [252]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean_23):
    # Rename column ('sleep_paralysis_frequency_score', 'narc_1900') to 'sleep_paralysis_frequency_score'
    fe_data_clean_23 = fe_data_clean_23.rename(columns={('sleep_paralysis_frequency_score', 'narc_1900'): 'sleep_paralysis_frequency_score'})
    # Rename column ('hypnagogic_hallucinations_(hh)_frequency_score', 'narc_2000') to 'hh_frequency_score'
    fe_data_clean_23 = fe_data_clean_23.rename(columns={('hypnagogic_hallucinations_(hh)_frequency_score', 'narc_2000'): 'hh_frequency_score'})
    # Drop columns: '('cataplexy_frequency_score_current', 'narc_2100')', '('cataplexy_frequency_score_before_treatment', 'narc_2110')', '('cataplexy_severity_score_current', 'narc_2200')'
    fe_data_clean_23 = fe_data_clean_23.drop(columns=[('cataplexy_frequency_score_current', 'narc_2100'), ('cataplexy_frequency_score_before_treatment', 'narc_2110'), ('cataplexy_severity_score_current', 'narc_2200')])
    # Rename column ('use_sleep_aids_at_least_once_per_week', 'mdhx_5600') to 'sleep_aids_min_once_per_week'
    fe_data_clean_23 = fe_data_clean_23.rename(columns={('use_sleep_aids_at_least_once_per_week', 'mdhx_5600'): 'sleep_aids_min_once_per_week'})
    # Rename column ('frequent_wakenings', 'map_0200') to 'frequent_wakenings_map'
    fe_data_clean_23 = fe_data_clean_23.rename(columns={('frequent_wakenings', 'map_0200'): 'frequent_wakenings_map'})
    # Rename column ('frequent_tossing_turning_thrashing', 'map_0500') to 'frequent_tossing_turning_map'
    fe_data_clean_23 = fe_data_clean_23.rename(columns={('frequent_tossing_turning_thrashing', 'map_0500'): 'frequent_tossing_turning_map'})
    # Drop columns: '('trivial_things_of_no_importance', 'tab_0100')', '('what_happened_today_and_what_you_have_to_do_tomorrow', 'tab_0200')' and 8 other columns
    fe_data_clean_23 = fe_data_clean_23.drop(columns=[('trivial_things_of_no_importance', 'tab_0100'), ('what_happened_today_and_what_you_have_to_do_tomorrow', 'tab_0200'), ('how_long_youve_been_lying_awake', 'tab_0300'), ('how_you_are_going_to_cope_tomorrow_if_you_dont_sleep_well_tonight', 'tab_0400'), ('noises_you_can_hear_in_the_house_or_outside', 'tab_0500'), ('your_heart_beat_pounding_in_your_head', 'tab_0700'), ('your_body_feeling_hot_or_cold', 'tab_0600'), ('how_out_of_control_your_sleep_is_and_you_dont_know_what_to_do_about_it', 'tab_0800'), ('things_that_have_happened_in_the_past_and_how_they_worked_out', 'tab_0900'), ('what_the_future_might_hold_and_what_you_should_do_for_things_to_work_out_well', 'tab_1000')])
    # Rename column ('difficulty_falling_asleep', 'isq_0100') to 'diff_falling_asleep_isq'
    fe_data_clean_23 = fe_data_clean_23.rename(columns={('difficulty_falling_asleep', 'isq_0100'): 'diff_falling_asleep_isq'})
    # Rename column ('difficulty_falling_asleep_number_of_times', 'isq_0110') to 'difficulty_falling_asleep_number_of_times'
    fe_data_clean_23 = fe_data_clean_23.rename(columns={('difficulty_falling_asleep_number_of_times', 'isq_0110'): 'difficulty_falling_asleep_number_of_times'})
    # Rename column ('difficulty_falling_asleep_time_frame', 'isq_0120') to 'difficulty_falling_asleep_time_frame'
    fe_data_clean_23 = fe_data_clean_23.rename(columns={('difficulty_falling_asleep_time_frame', 'isq_0120'): 'difficulty_falling_asleep_time_frame'})
    # Rename column ('difficulty_staying_asleep', 'isq_0200') to 'difficulty_staying_asleep'
    fe_data_clean_23 = fe_data_clean_23.rename(columns={('difficulty_staying_asleep', 'isq_0200'): 'difficulty_staying_asleep'})
    # Rename column ('difficulty_staying_asleep_number', 'isq_0210') to 'difficulty_staying_asleep_number'
    fe_data_clean_23 = fe_data_clean_23.rename(columns={('difficulty_staying_asleep_number', 'isq_0210'): 'difficulty_staying_asleep_number'})
    # Rename column ('difficulty_staying_asleep_time_frame', 'isq_0220') to 'difficulty_staying_asleep_time_frame'
    fe_data_clean_23 = fe_data_clean_23.rename(columns={('difficulty_staying_asleep_time_frame', 'isq_0220'): 'difficulty_staying_asleep_time_frame'})
    # Rename column ('multiple_awakenings', 'isq_0300') to 'multiple_awakenings'
    fe_data_clean_23 = fe_data_clean_23.rename(columns={('multiple_awakenings', 'isq_0300'): 'multiple_awakenings'})
    # Rename column ('multiple_awakenings_number', 'isq_0310') to 'multiple_awakenings_number'
    fe_data_clean_23 = fe_data_clean_23.rename(columns={('multiple_awakenings_number', 'isq_0310'): 'multiple_awakenings_number'})
    # Rename column ('multiple_awakenings_time_frame', 'isq_0320') to 'multiple_awakenings_time_frame'
    fe_data_clean_23 = fe_data_clean_23.rename(columns={('multiple_awakenings_time_frame', 'isq_0320'): 'multiple_awakenings_time_frame'})
    return fe_data_clean_23

fe_data_clean_24 = clean_data(fe_data_clean_23.copy())
fe_data_clean_24.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3

In [253]:
"""
merging features into strings
"""

time_frame_mappings = {0: "per week", 1: "per month", 2: "per year"}

fe_data_clean_24["diff_falling_asleep_time_frame"] = fe_data_clean_24[
    "difficulty_falling_asleep_time_frame"
].map(time_frame_mappings)

fe_data_clean_24["diff_staying_asleep_time_frame"] = fe_data_clean_24[
    "difficulty_staying_asleep_time_frame"
].map(time_frame_mappings)

fe_data_clean_24["multiple_awakenings_time_frame"] = fe_data_clean_24[
    "multiple_awakenings_time_frame"
].map(time_frame_mappings)

fe_data_clean_24["diff_falling_asleep_freq"] = (
    fe_data_clean_24["difficulty_falling_asleep_number_of_times"].astype(str)
    + " "
    + fe_data_clean_24["diff_falling_asleep_time_frame"]
)

fe_data_clean_24["diff_staying_asleep_freq"] = (
    fe_data_clean_24["difficulty_staying_asleep_number"].astype(str)
    + " "
    + fe_data_clean_24["diff_staying_asleep_time_frame"]
)
fe_data_clean_24["multiple_awakenings_freq"] = (
    fe_data_clean_24["multiple_awakenings_number"].astype(str)
    + " "
    + fe_data_clean_24["multiple_awakenings_time_frame"]
)

fe_data_clean_24["difficulty_falling_asleep_number_of_times"] = fe_data_clean_24[
    "diff_falling_asleep_freq"
]
fe_data_clean_24["difficulty_staying_asleep_number"] = fe_data_clean_24[
    "diff_staying_asleep_freq"
]
fe_data_clean_24["multiple_awakenings_number"] = fe_data_clean_24[
    "multiple_awakenings_freq"
]

fe_data_clean_24 = fe_data_clean_24.drop(
    columns=[
        "difficulty_falling_asleep_time_frame",
        "difficulty_staying_asleep_time_frame",
        "multiple_awakenings_time_frame",
        "diff_falling_asleep_freq",
        "diff_staying_asleep_freq",
        "multiple_awakenings_freq",
    ]
)

fe_data_clean_24.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)",diff_falling_asleep_time_frame,diff_staying_asleep_time_frame
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3,NaN,NaN
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4,per year,per year
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,per year,per year
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9,per year,per year
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,4,4,3,3,1,0,1.3,per month,per year

In [254]:
"""
Cell generated by Data Wrangler.
more renaming
"""
def clean_data(fe_data_clean_24):
    # Rename column 'difficulty_falling_asleep_number_of_times' to 'difficulty_falling_asleep_num_isq'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={'difficulty_falling_asleep_number_of_times': 'difficulty_falling_asleep_num_isq'})
    # Rename column 'difficulty_staying_asleep_number' to 'difficulty_staying_asleep_num_isq'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={'difficulty_staying_asleep_number': 'difficulty_staying_asleep_num_isq'})
    # Rename column 'multiple_awakenings_number' to 'multiple_awakenings_num_isq'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={'multiple_awakenings_number': 'multiple_awakenings_num_isq'})
    # Rename column 'difficulty_staying_asleep' to 'difficulty_staying_asleep_isq'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={'difficulty_staying_asleep': 'difficulty_staying_asleep_isq'})
    # Rename column 'multiple_awakenings' to 'multiple_awakenings_isq'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={'multiple_awakenings': 'multiple_awakenings_isq'})
    # Rename column ('meets_diagnostic_insomnia_criteria', 'isq_score') to 'meets_criteria_isq'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('meets_diagnostic_insomnia_criteria', 'isq_score'): 'meets_criteria_isq'})
    # Rename column ('wake_hrs_sch_work_nights', 'sched_2500') to 'hrs_awake_night_sw'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('wake_hrs_sch_work_nights', 'sched_2500'): 'hrs_awake_night_sw'})
    # Rename column ('wake_hrs_non_sch_non_work_nights', 'sched_3900') to 'hrs_awake_night_no_sw'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('wake_hrs_non_sch_non_work_nights', 'sched_3900'): 'hrs_awake_night_no_sw'})
    # Rename column ('num_awakens_sch_work_nights', 'sched_24000') to 'num_awakens_night_sw'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('num_awakens_sch_work_nights', 'sched_24000'): 'num_awakens_night_sw'})
    # Rename column ('num_awakens_non_sch_non_work_nights', 'sched_3900') to 'num_awakens_night_no_sw'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('num_awakens_non_sch_non_work_nights', 'sched_3900'): 'num_awakens_night_no_sw'})
    # Rename column ('previously_been_to_a_sleep_specialist', 'mdhx_0200') to 'prev_been_to_sleep_specialist'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('previously_been_to_a_sleep_specialist', 'mdhx_0200'): 'prev_been_to_sleep_specialist'})
    # Rename column ('trigger_for_sleep_disorder', 'mdhx_5500') to 'trigger_for_slp_disorder_mdhx'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('trigger_for_sleep_disorder', 'mdhx_5500'): 'trigger_for_slp_disorder_mdhx'})
    # Rename column ('loud_snoring', 'map_0100') to 'loud_snoring_map'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('loud_snoring', 'map_0100'): 'loud_snoring_map'})
    # Rename column ('snorting_gasping', 'map_0300') to 'snorting_gasping_map'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('snorting_gasping', 'map_0300'): 'snorting_gasping_map'})
    # Rename column ('fall_asleep_at_work', 'map_0400') to 'fall_asleep_at_work_map'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('fall_asleep_at_work', 'map_0400'): 'fall_asleep_at_work_map'})
    # Rename column ('breathing_stops', 'map_0600') to 'breathing_stops_map'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('breathing_stops', 'map_0600'): 'breathing_stops_map'})
    # Rename column ('excessive_sleepiness', 'map_0700') to 'excessive_sleepiness_map'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('excessive_sleepiness', 'map_0700'): 'excessive_sleepiness_map'})
    # Rename column ('morning_headache', 'map_0800') to 'morning_headache_map'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('morning_headache', 'map_0800'): 'morning_headache_map'})
    # Rename column ('fall_asleep_driving', 'map_0900') to 'fall_asleep_driving_map'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('fall_asleep_driving', 'map_0900'): 'fall_asleep_driving_map'})
    # Rename column ('map_index_1_apnea_score', 'index_1') to 'map_index_1_apnea_score'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('map_index_1_apnea_score', 'index_1'): 'map_index_1_apnea_score'})
    # Rename column ('map_index_3_excessive_daytime_sleepiness_(eds)_score', 'index_3') to 'map_index_3_excessive_daytime_sleepiness_'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('map_index_3_excessive_daytime_sleepiness_(eds)_score', 'index_3'): 'map_index_3_excessive_daytime_sleepiness_'})
    # Rename column ('map_likelihood_ration_(lr)', 'map_lr') to 'map_likelihood_ration'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('map_likelihood_ration_(lr)', 'map_lr'): 'map_likelihood_ration'})
    # Rename column ('map_score', 'score') to 'map_score'
    fe_data_clean_24 = fe_data_clean_24.rename(columns={('map_score', 'score'): 'map_score'})
    return fe_data_clean_24

fe_data_clean_25 = clean_data(fe_data_clean_24.copy())
fe_data_clean_25.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)",diff_falling_asleep_time_frame,diff_staying_asleep_time_frame
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3,NaN,NaN
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4,per year,per year
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,per year,per year
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9,per year,per year
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,4,4,3,3,1,0,1.3,per month,per year

In [255]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean_25):
    # Rename column ('epworth_sleepiness_scale_chance_of_dozing_while_watching_tv', 'ess_0200') to 'ess_chance_of_dozing_tv'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('epworth_sleepiness_scale_chance_of_dozing_while_watching_tv', 'ess_0200'): 'ess_chance_of_dozing_tv'})
    # Rename column ('epworth_sleepiness_scale_chance_of_dozing_while_sitting_inactive_in_a_public_place', 'ess_0300') to 'ess_chance_of_dozing_inactive_public'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('epworth_sleepiness_scale_chance_of_dozing_while_sitting_inactive_in_a_public_place', 'ess_0300'): 'ess_chance_of_dozing_inactive_public'})
    # Rename column ('epworth_sleepiness_scale_chance_of_dozing_as_a_passenger_in_a_car_for_an_hour_without_a_break', 'ess_0400') to 'ess_chance_of_dozing_car_passenger_hr'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('epworth_sleepiness_scale_chance_of_dozing_as_a_passenger_in_a_car_for_an_hour_without_a_break', 'ess_0400'): 'ess_chance_of_dozing_car_passenger_hr'})
    # Rename column ('epworth_sleepiness_scale_chance_of_dozing_while_lying_down_in_the_afternoon_when_circumstances_permit', 'ess_0500') to 'ess_chance_of_dozing_lying_down_in_afternoon_when_circumstances_permit'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('epworth_sleepiness_scale_chance_of_dozing_while_lying_down_in_the_afternoon_when_circumstances_permit', 'ess_0500'): 'ess_chance_of_dozing_lying_down_in_afternoon_when_circumstances_permit'})
    # Rename column ('epworth_sleepiness_scale_chance_of_dozing_while_sitting_and_talking_to_someone', 'ess_0600') to 'ess_chance_of_dozing_sitting_and_talking_to_someone'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('epworth_sleepiness_scale_chance_of_dozing_while_sitting_and_talking_to_someone', 'ess_0600'): 'ess_chance_of_dozing_sitting_and_talking_to_someone'})
    # Rename column ('epworth_sleepiness_scale_chance_of_dozing_while_sitting_quietly_after_lunch_without_alcohol', 'ess_0700') to 'ess_chance_of_dozing_sitting_quietly_after_lunch_without_alcohol'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('epworth_sleepiness_scale_chance_of_dozing_while_sitting_quietly_after_lunch_without_alcohol', 'ess_0700'): 'ess_chance_of_dozing_sitting_quietly_after_lunch_without_alcohol'})
    # Rename column ('epworth_sleepiness_scale_chance_of_dozing_while_in_a_car_while_stopped_for_a_few_minutes_in_traffic', 'ess_0800') to 'ess_chance_of_dozing_in_a_car_while_stopped_for_few_minutes_in_traffic'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('epworth_sleepiness_scale_chance_of_dozing_while_in_a_car_while_stopped_for_a_few_minutes_in_traffic', 'ess_0800'): 'ess_chance_of_dozing_in_a_car_while_stopped_for_few_minutes_in_traffic'})
    # Rename column ('epworth_sleepiness_scale_total_score', 'ess_0900') to 'ess_total_score'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('epworth_sleepiness_scale_total_score', 'ess_0900'): 'ess_total_score'})
    # Rename column ('difficulty_staying_awake_during_the_day_never', 'slpy_0101') to 'diff_staying_awake_during_day_never'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('difficulty_staying_awake_during_the_day_never', 'slpy_0101'): 'diff_staying_awake_during_day_never'})
    # Rename column ('difficulty_staying_awake_during_the_day_number_of_times', 'slpy_0100') to 'difficulty_staying_awake_during_the_day_number_of_times'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('difficulty_staying_awake_during_the_day_number_of_times', 'slpy_0100'): 'difficulty_staying_awake_during_the_day_number_of_times'})
    # Rename column ('difficulty_staying_awake_during_the_day_time_frame', 'slpy_0110') to 'difficulty_staying_awake_during_the_day_time_frame'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('difficulty_staying_awake_during_the_day_time_frame', 'slpy_0110'): 'difficulty_staying_awake_during_the_day_time_frame'})
    # Rename column ('sleep_attacks_never', 'slpy_0201') to 'sleep_attacks_never'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('sleep_attacks_never', 'slpy_0201'): 'sleep_attacks_never'})
    # Rename column ('sleep_attacks_number_of_times', 'slpy_0200') to 'sleep_attacks_number_of_times'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('sleep_attacks_number_of_times', 'slpy_0200'): 'sleep_attacks_number_of_times'})
    # Rename column ('sleep_attacks_time_frame', 'slpy_0210') to 'sleep_attacks_time_frame'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('sleep_attacks_time_frame', 'slpy_0210'): 'sleep_attacks_time_frame'})
    # Rename column ('perform_activities_without_awareness_when_sleepy_never', 'slpy_0301') to 'perform_activities_without_awareness_when_sleepy_never'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('perform_activities_without_awareness_when_sleepy_never', 'slpy_0301'): 'perform_activities_without_awareness_when_sleepy_never'})
    # Rename column ('perform_activities_without_awareness_when_sleepy_number_of_times', 'slpy_0300') to 'perform_activities_without_awareness_when_sleepy_number_of_times'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('perform_activities_without_awareness_when_sleepy_number_of_times', 'slpy_0300'): 'perform_activities_without_awareness_when_sleepy_number_of_times'})
    # Rename column ('perform_activities_without_awareness_when_sleepy_time_frame', 'slpy_0310') to 'perform_activities_without_awareness_when_sleepy_time_frame'
    fe_data_clean_25 = fe_data_clean_25.rename(columns={('perform_activities_without_awareness_when_sleepy_time_frame', 'slpy_0310'): 'perform_activities_without_awareness_when_sleepy_time_frame'})
    return fe_data_clean_25

fe_data_clean_26 = clean_data(fe_data_clean_25.copy())
fe_data_clean_26.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)",diff_falling_asleep_time_frame,diff_staying_asleep_time_frame
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3,NaN,NaN
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4,per year,per year
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,per year,per year
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9,per year,per year
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,4,4,3,3,1,0,1.3,per month,per year

In [256]:
"""
combine slpy features yayyyyyyy

they are all dayyear mapping
"""

day_year_mapping = {0: "Day", 1: "Week", 2: "Month", 3: "Year"}

fe_data_clean_26["difficulty_staying_awake_during_the_day_time_frame"] = (
    fe_data_clean_26["difficulty_staying_awake_during_the_day_time_frame"].map(
        day_year_mapping
    )
)

fe_data_clean_26["sleep_attacks_time_frame"] = fe_data_clean_26[
    "sleep_attacks_time_frame"
].map(day_year_mapping)

fe_data_clean_26["perform_activities_without_awareness_when_sleepy_time_frame"] = (
    fe_data_clean_26["perform_activities_without_awareness_when_sleepy_time_frame"].map(
        day_year_mapping
    )
)

fe_data_clean_26["diff_staying_awake_during_day_freq"] = (
    fe_data_clean_26["difficulty_staying_awake_during_the_day_number_of_times"].astype(
        str
    )
    + " "
    + fe_data_clean_26["difficulty_staying_awake_during_the_day_time_frame"]
)

fe_data_clean_26["sleep_attacks_freq"] = (
    fe_data_clean_26["sleep_attacks_number_of_times"].astype(str)
    + " "
    + fe_data_clean_26["sleep_attacks_time_frame"]
)

fe_data_clean_26["perform_activities_without_awareness_when_sleepy_freq"] = (
    fe_data_clean_26[
        "perform_activities_without_awareness_when_sleepy_number_of_times"
    ].astype(str)
    + " "
    + fe_data_clean_26["perform_activities_without_awareness_when_sleepy_time_frame"]
)

fe_data_clean_26 = fe_data_clean_26.astype(
    {"difficulty_staying_awake_during_the_day_number_of_times": "string"}
)
fe_data_clean_26 = fe_data_clean_26.astype({"sleep_attacks_number_of_times": "string"})
fe_data_clean_26 = fe_data_clean_26.astype(
    {"perform_activities_without_awareness_when_sleepy_number_of_times": "string"}
)

fe_data_clean_26["difficulty_staying_awake_during_the_day_number_of_times"] = (
    fe_data_clean_26["diff_staying_awake_during_day_freq"]
)
fe_data_clean_26["sleep_attacks_number_of_times"] = fe_data_clean_26[
    "sleep_attacks_freq"
]
fe_data_clean_26["perform_activities_without_awareness_when_sleepy_number_of_times"] = (
    fe_data_clean_26["perform_activities_without_awareness_when_sleepy_freq"]
)

fe_data_clean_26 = fe_data_clean_26.drop(
    columns=[
        "difficulty_staying_awake_during_the_day_time_frame",
        "sleep_attacks_time_frame",
        "perform_activities_without_awareness_when_sleepy_time_frame",
        "diff_staying_awake_during_day_freq",
        "sleep_attacks_freq",
        "perform_activities_without_awareness_when_sleepy_freq",
    ]
)

fe_data_clean_26.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)",diff_falling_asleep_time_frame,diff_staying_asleep_time_frame
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3,NaN,NaN
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4,per year,per year
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,per year,per year
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9,per year,per year
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,4,4,3,3,1,0,1.3,per month,per year

In [257]:
"""
Cell generated by Data Wrangler.
I forgot this oops
"""
def clean_data(fe_data_clean_26):
    # Rename column ('epworth_sleepiness_scale_chance_of_dozing_while_sitting_and_reading', 'ess_0100') to 'ess_chance_of_dozing_sitting_and_reading'
    fe_data_clean_26 = fe_data_clean_26.rename(columns={('epworth_sleepiness_scale_chance_of_dozing_while_sitting_and_reading', 'ess_0100'): 'ess_chance_of_dozing_sitting_and_reading'})
    return fe_data_clean_26

fe_data_clean_27 = clean_data(fe_data_clean_26.copy())
fe_data_clean_27.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)",diff_falling_asleep_time_frame,diff_staying_asleep_time_frame
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3,NaN,NaN
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4,per year,per year
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,per year,per year
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9,per year,per year
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,4,4,3,3,1,0,1.3,per month,per year

In [258]:
""" 
adding the never guys to the previous features
"""

fe_data_clean_27["difficulty_staying_awake_during_the_day_number_of_times"] = np.where(
    fe_data_clean_27["diff_staying_awake_during_day_never"].fillna(False),
    "rarely or never",
    fe_data_clean_27["difficulty_staying_awake_during_the_day_number_of_times"]
)

fe_data_clean_27["sleep_attacks_number_of_times"] = np.where(
    fe_data_clean_27["sleep_attacks_never"].fillna(False),
    "rarely or never",
    fe_data_clean_27["sleep_attacks_number_of_times"],
)

fe_data_clean_27["perform_activities_without_awareness_when_sleepy_number_of_times"] = np.where(
    fe_data_clean_27["perform_activities_without_awareness_when_sleepy_never"].fillna(
        False
    ),
    "rarely or never",
    fe_data_clean_27[
        "perform_activities_without_awareness_when_sleepy_number_of_times"
    ],
)

fe_data_clean_27 = fe_data_clean_27.drop(
    columns=[
        "diff_staying_awake_during_day_never",
        "sleep_attacks_never",
        "perform_activities_without_awareness_when_sleepy_never",
    ]
)

fe_data_clean_27.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)",diff_falling_asleep_time_frame,diff_staying_asleep_time_frame
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3,NaN,NaN
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4,per year,per year
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,per year,per year
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9,per year,per year
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,4,4,3,3,1,0,1.3,per month,per year

In [259]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean_27):
    # Rename column ('had_an_accident_or_near_miss_due_to_sleepiness_number_of_event', 'slpy_0400') to 'num_accident_or_near_miss_due_to_sleepiness'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('had_an_accident_or_near_miss_due_to_sleepiness_number_of_event', 'slpy_0400'): 'num_accident_or_near_miss_due_to_sleepiness'})
    # Rename column ('had_an_accident_or_near_miss_due_to_sleepiness_last_occurrence', 'slpy_0410') to 'last_occurance_accident_or_near_miss_due_to_sleepiness'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('had_an_accident_or_near_miss_due_to_sleepiness_last_occurrence', 'slpy_0410'): 'last_occurance_accident_or_near_miss_due_to_sleepiness'})
    # Rename column ('insomnia_severity_index_difficulty_falling_asleep', 'isi_0100') to 'diff_falling_asleep_isi'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('insomnia_severity_index_difficulty_falling_asleep', 'isi_0100'): 'diff_falling_asleep_isi'})
    # Rename column ('insomnia_severity_index_difficulty_staying_asleep', 'isi_0200') to 'diff_staying_asleep_isi'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('insomnia_severity_index_difficulty_staying_asleep', 'isi_0200'): 'diff_staying_asleep_isi'})
    # Rename column ('insomnia_severity_index_problems_waking_up_too_early', 'isi_0300') to 'problems_waking_up_too_early_isi'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('insomnia_severity_index_problems_waking_up_too_early', 'isi_0300'): 'problems_waking_up_too_early_isi'})
    # Rename column ('insomnia_severity_index_how_satisfied_with_current_sleep_pattern', 'isi_0400') to 'how_satisfied_with_curr_sleep_pattern_isi'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('insomnia_severity_index_how_satisfied_with_current_sleep_pattern', 'isi_0400'): 'how_satisfied_with_curr_sleep_pattern_isi'})
    # Rename column ('insomnia_severity_index_how_noticeable_to_others_is_sleep_problem_impacting_quality_of_life', 'isi_0500') to 'how_noticeable_is_sleep_problem_impacting_quality_of_life_isi'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('insomnia_severity_index_how_noticeable_to_others_is_sleep_problem_impacting_quality_of_life', 'isi_0500'): 'how_noticeable_is_sleep_problem_impacting_quality_of_life_isi'})
    # Rename column ('insomnia_severity_index_how_worried/distressed_about_current_sleep_problem', 'isi_0600') to 'how_worried_about_current_sleep_problem_isi'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('insomnia_severity_index_how_worried/distressed_about_current_sleep_problem', 'isi_0600'): 'how_worried_about_current_sleep_problem_isi'})
    # Rename column ('insomnia_severity_index_sleep_problem_intereferes_with_daily_functioning', 'isi_0700') to 'sleep_problem_intereferes_with_daily_functioning_isi'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('insomnia_severity_index_sleep_problem_intereferes_with_daily_functioning', 'isi_0700'): 'sleep_problem_intereferes_with_daily_functioning_isi'})
    # Rename column ('insomnia_severity_index_total_score', 'isi_score') to 'isi_total_score'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('insomnia_severity_index_total_score', 'isi_score'): 'isi_total_score'})
    # Rename column ('sleep_affected_work', 'isq_0700') to 'sleep_affected_work_isq'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('sleep_affected_work', 'isq_0700'): 'sleep_affected_work_isq'})
    # Rename column ('sleep_affected_your_social_life', 'isq_0800') to 'sleep_affected_your_social_life_isq'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('sleep_affected_your_social_life', 'isq_0800'): 'sleep_affected_your_social_life_isq'})
    # Rename column ('sleep_affected_other_important_parts_of_life', 'isq_0900') to 'sleep_affected_other_important_parts_of_life'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('sleep_affected_other_important_parts_of_life', 'isq_0900'): 'sleep_affected_other_important_parts_of_life'})
    # Rename column 'sleep_affected_other_important_parts_of_life' to 'sleep_affected_other_important_parts_of_life_isq'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={'sleep_affected_other_important_parts_of_life': 'sleep_affected_other_important_parts_of_life_isq'})
    # Rename column ('sleep_made_you_irritable', 'isq_1000') to 'sleep_made_you_irritable_isq'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('sleep_made_you_irritable', 'isq_1000'): 'sleep_made_you_irritable_isq'})
    # Rename column ('sleep_caused_trouble_concentrating', 'isq_1100') to 'sleep_caused_trouble_concentrating_isq'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('sleep_caused_trouble_concentrating', 'isq_1100'): 'sleep_caused_trouble_concentrating_isq'})
    # Rename column ('sleep_made_you_fatigued', 'isq_1200') to 'sleep_made_you_fatigued_isq'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('sleep_made_you_fatigued', 'isq_1200'): 'sleep_made_you_fatigued_isq'})
    # Rename column ('how_sleepy_do_you_feel_during_the_day', 'isq_1300') to 'how_sleepy_do_you_feel_during_the_day_isq'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('how_sleepy_do_you_feel_during_the_day', 'isq_1300'): 'how_sleepy_do_you_feel_during_the_day_isq'})
    # Drop columns: '('horne-ostberg_morningness-eveningness_questionnaire_time_of_day_reaching_"feeling_best"_peak', 'cir_0500')', '('horne-ostberg_morningness-eveningness_questionnaire_time_of_evening_you_need_sleep', 'cir_0400')' and 2 other columns
    fe_data_clean_27 = fe_data_clean_27.drop(columns=[('horne-ostberg_morningness-eveningness_questionnaire_time_of_day_reaching_"feeling_best"_peak', 'cir_0500'), ('horne-ostberg_morningness-eveningness_questionnaire_time_of_evening_you_need_sleep', 'cir_0400'), ('horne-ostberg_morningness-eveningness_questionnaire_tiredness_during_first_half-hour_after_waking', 'cir_0300'), ('horne-ostberg_morningness-eveningness_questionnaire_ideal_scheduled_wake_time', 'cir_0200')])
    # Rename column ('horne-ostberg_morningness-eveningness_questionnaire_morning_or_evening_type', 'cir_0600') to 'horne_ostberg_morn_or_evening_type'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('horne-ostberg_morningness-eveningness_questionnaire_morning_or_evening_type', 'cir_0600'): 'horne_ostberg_morn_or_evening_type'})
    # Rename column ('rmeq_total_score', 'cir_0700') to 'rmeq_total_score'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('rmeq_total_score', 'cir_0700'): 'rmeq_total_score'})
    # Rename column ('remember_dreams_times', 'par_0900') to 'remember_dreams_times'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('remember_dreams_times', 'par_0900'): 'remember_dreams_times'})
    # Rename column ('remember_dreams_never_or_dont_know', 'par_0901') to 'remember_dreams_never_or_dont_know'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('remember_dreams_never_or_dont_know', 'par_0901'): 'remember_dreams_never_or_dont_know'})
    # Rename column ('remember_dreams_time_frame', 'par_0910') to 'remember_dreams_time_frame'
    fe_data_clean_27 = fe_data_clean_27.rename(columns={('remember_dreams_time_frame', 'par_0910'): 'remember_dreams_time_frame'})
    return fe_data_clean_27

fe_data_clean_28 = clean_data(fe_data_clean_27.copy())
fe_data_clean_28.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)",diff_falling_asleep_time_frame,diff_staying_asleep_time_frame
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3,NaN,NaN
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4,per year,per year
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,per year,per year
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9,per year,per year
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,4,4,3,3,1,0,1.3,per month,per year

In [260]:
"""
merging more columns womp womp 
remember_dreams_times; week month year
"""

wmy_mapping  = {0: "per week", 1: "per month", 2: "per year"}

fe_data_clean_28["remember_dreams_time_frame"] = fe_data_clean_28[
    "remember_dreams_time_frame"].map(wmy_mapping)

fe_data_clean_28["remember_dreams_freq"] = (
    fe_data_clean_28["remember_dreams_times"].astype(str)
    + " "
    + fe_data_clean_28["remember_dreams_time_frame"]
)

fe_data_clean_28 = fe_data_clean_28.astype({"remember_dreams_times": "string"})

fe_data_clean_28["remember_dreams_times"] = fe_data_clean_28["remember_dreams_freq"]
fe_data_clean_28 = fe_data_clean_28.drop(columns=["remember_dreams_time_frame", "remember_dreams_freq"])

fe_data_clean_28['remember_dreams_times'] = np.where(
    fe_data_clean_28['remember_dreams_never_or_dont_know'].fillna(False),
    'rarely or never',
    fe_data_clean_28['remember_dreams_times'])

fe_data_clean_28 = fe_data_clean_28.drop(columns=['remember_dreams_never_or_dont_know'])
fe_data_clean_28.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,"(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)",diff_falling_asleep_time_frame,diff_staying_asleep_time_frame
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3,NaN,NaN
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4,per year,per year
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,per year,per year
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9,per year,per year
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,4,4,3,3,1,0,1.3,per month,per year

In [261]:
"""
Cell generated by Data Wrangler.
all features renamed :) 
"""
def clean_data(fe_data_clean_28):
    # Rename column ('functional_outcomes_of_sleep_difficulty_concentrating', 'fosq_0100') to 'difficulty_concentrating_fosq'
    fe_data_clean_28 = fe_data_clean_28.rename(columns={('functional_outcomes_of_sleep_difficulty_concentrating', 'fosq_0100'): 'difficulty_concentrating_fosq'})
    # Rename column ('functional_outcomes_of_sleep_difficulty_remembering', 'fosq_0200') to 'difficulty_remembering_fosq'
    fe_data_clean_28 = fe_data_clean_28.rename(columns={('functional_outcomes_of_sleep_difficulty_remembering', 'fosq_0200'): 'difficulty_remembering_fosq'})
    # Rename column ('functional_outcomes_of_sleep_difficulty_operating_motor_vehicles_for_short_distances_(less_than_100_miles)', 'fosq_0300') to 'difficulty_operating_motor_vehicles_for_short_distances_fosq'
    fe_data_clean_28 = fe_data_clean_28.rename(columns={('functional_outcomes_of_sleep_difficulty_operating_motor_vehicles_for_short_distances_(less_than_100_miles)', 'fosq_0300'): 'difficulty_operating_motor_vehicles_for_short_distances_fosq'})
    # Rename column ('functional_outcomes_of_sleep_difficulty_operating_motor_vehicles_for_long_distances_(greater_than_100_miles)', 'fosq_0400') to 'difficulty_operating_motor_vehicles_for_long_distances_fosq'
    fe_data_clean_28 = fe_data_clean_28.rename(columns={('functional_outcomes_of_sleep_difficulty_operating_motor_vehicles_for_long_distances_(greater_than_100_miles)', 'fosq_0400'): 'difficulty_operating_motor_vehicles_for_long_distances_fosq'})
    # Rename column ('functional_outcomes_of_sleep_difficulty_visiting_family_or_friends_in_their_home', 'fosq_0500') to 'difficulty_visiting_family_or_friends_in_their_home_fosq'
    fe_data_clean_28 = fe_data_clean_28.rename(columns={('functional_outcomes_of_sleep_difficulty_visiting_family_or_friends_in_their_home', 'fosq_0500'): 'difficulty_visiting_family_or_friends_in_their_home_fosq'})
    # Rename column ('functional_outcomes_of_sleep_relationships_with_family_or_friends_affected', 'fosq_0600') to 'relationships_with_family_or_friends_affected_fosq'
    fe_data_clean_28 = fe_data_clean_28.rename(columns={('functional_outcomes_of_sleep_relationships_with_family_or_friends_affected', 'fosq_0600'): 'relationships_with_family_or_friends_affected_fosq'})
    # Rename column ('functional_outcomes_of_sleep_difficulty_watching_a_movie', 'fosq_0700') to 'difficulty_watching_a_movie_fosq'
    fe_data_clean_28 = fe_data_clean_28.rename(columns={('functional_outcomes_of_sleep_difficulty_watching_a_movie', 'fosq_0700'): 'difficulty_watching_a_movie_fosq'})
    # Rename column ('functional_outcomes_of_sleep_difficulty_being_active_in_evening', 'fosq_0800') to 'difficulty_being_active_in_evening_fosq'
    fe_data_clean_28 = fe_data_clean_28.rename(columns={('functional_outcomes_of_sleep_difficulty_being_active_in_evening', 'fosq_0800'): 'difficulty_being_active_in_evening_fosq'})
    # Rename column ('functional_outcomes_of_sleep_difficulty_being_active_in_morning', 'fosq_0900') to 'difficulty_being_active_in_morning_fosq'
    fe_data_clean_28 = fe_data_clean_28.rename(columns={('functional_outcomes_of_sleep_difficulty_being_active_in_morning', 'fosq_0900'): 'difficulty_being_active_in_morning_fosq'})
    # Rename column ('functional_outcomes_of_sleep_effect_on_desire_for_intimacy_or_sex', 'fosq_1000') to 'effect_on_desire_for_intimacy_or_sex_fosq'
    fe_data_clean_28 = fe_data_clean_28.rename(columns={('functional_outcomes_of_sleep_effect_on_desire_for_intimacy_or_sex', 'fosq_1000'): 'effect_on_desire_for_intimacy_or_sex_fosq'})
    # Rename column ('functional_outcomes_of_sleep_summary_score', 'fosq_1100') to 'fosq_summary_score'
    fe_data_clean_28 = fe_data_clean_28.rename(columns={('functional_outcomes_of_sleep_summary_score', 'fosq_1100'): 'fosq_summary_score'})
    # Drop columns: 'diff_falling_asleep_time_frame', 'diff_staying_asleep_time_frame' and 18 other columns
    fe_data_clean_28 = fe_data_clean_28.drop(columns=['diff_falling_asleep_time_frame', 'diff_staying_asleep_time_frame', ('do_you_use_a_chin_strap', 'pap_2100'), ('how_do_you_feel_about_your_current_mask', 'pap_1900'), ('when_was_the_last_time_you_checked_or_changed_your_tube', 'pap_1800'), ('when_was_the_last_time_you_checked_or_changed_your_filters', 'pap_1700'), ('when_was_the_last_time_you_replaced_your_mask', 'pap_1600'), ('my_mask_size', 'pap_1400'), ('my_current_mask_type', 'pap_1300'), ('how_often_do_you_get_water_in_my_tubing/_mask', 'pap_1200'), ('how_often_do_you_use_your_heated_humidifier', 'pap_0800'), ('does_your_pap_have_a_heated_tube', 'pap_0700'), ('do_you_use_a_heated_humidifier', 'pap_0600'), ('forget_to_take_your_pap_when_you_travel', 'pap_0500'), ('forget_to_use_your_pap_with_naps', 'pap_0400'), ('forget_to_put_mask_on_after_bathroom', 'pap_0300'), ('remove_your_mask_unknowingly_while_sleeping', 'pap_0200'), ('fall_asleep_before_your_mask/_pap_is_on', 'pap_0100'), ('on_nights_pap_was_used_how_many_hours_of_pap_use', 'mdhx_0800'), ('frequency_of_pap_use', 'mdhx_0700')])
    # Rename column ('type_of_pap_device', 'mdhx_0400') to 'type_of_pap_device'
    fe_data_clean_28 = fe_data_clean_28.rename(columns={('type_of_pap_device', 'mdhx_0400'): 'type_of_pap_device'})
    # Rename column ('apnea_hypopnea_index', 'ahi') to 'ahi'
    fe_data_clean_28 = fe_data_clean_28.rename(columns={('apnea_hypopnea_index', 'ahi'): 'ahi'})
    return fe_data_clean_28

fe_data_clean_29 = clean_data(fe_data_clean_28.copy())
fe_data_clean_29.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,difficulty_operating_motor_vehicles_for_long_distances_fosq,difficulty_visiting_family_or_friends_in_their_home_fosq,relationships_with_family_or_friends_affected_fosq,difficulty_watching_a_movie_fosq,difficulty_being_active_in_evening_fosq,difficulty_being_active_in_morning_fosq,effect_on_desire_for_intimacy_or_sex_fosq,fosq_summary_score,type_of_pap_device,ahi
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,2,1,1,2,1.0,1.0,2,8,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,4,3,3,3,3.0,3.0,3,14,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,4,3,4,3,2.0,2.0,4,16,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,4,4,3,3,2.0,2.0,2,15,False,1.3

In [262]:
"""
Cell generated by Data Wrangler.
i am going to remove all weekend features becasue they overcomplicate
"""
def clean_data(fe_data_clean_29):
    # Drop columns: 'bedtime_no_sw_varies', 'bedtime_no_sw' and 2 other columns
    fe_data_clean_29 = fe_data_clean_29.drop(columns=['bedtime_no_sw_varies', 'bedtime_no_sw', 'wakeup_no_sw', 'wakeup_no_sw_varies'])
    # Drop columns: 'latency_no_sw', 'total_slp_duration_no_sw', 'slp_quality_no_sw'
    fe_data_clean_29 = fe_data_clean_29.drop(columns=['latency_no_sw', 'total_slp_duration_no_sw', 'slp_quality_no_sw'])
    # Drop columns: 'hrs_awake_night_no_sw', 'num_awakens_night_no_sw'
    fe_data_clean_29 = fe_data_clean_29.drop(columns=['hrs_awake_night_no_sw', 'num_awakens_night_no_sw'])
    return fe_data_clean_29

fe_data_clean_30 = clean_data(fe_data_clean_29.copy())
fe_data_clean_30.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,difficulty_operating_motor_vehicles_for_long_distances_fosq,difficulty_visiting_family_or_friends_in_their_home_fosq,relationships_with_family_or_friends_affected_fosq,difficulty_watching_a_movie_fosq,difficulty_being_active_in_evening_fosq,difficulty_being_active_in_morning_fosq,effect_on_desire_for_intimacy_or_sex_fosq,fosq_summary_score,type_of_pap_device,ahi
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,2,1,1,2,1.0,1.0,2,8,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,4,3,3,3,3.0,3.0,3,14,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,4,3,4,3,2.0,2.0,4,16,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,4,4,3,3,2.0,2.0,2,15,False,1.3

In [263]:
"""
caffeine consumption fe
"""
fe_data_clean_30 = fe_data_clean_30.rename(columns={('caffeine_consumption_time_of_last_drink', 'soclhx_1000') : 'caffeine_consumption_time_of_last_drink'})

temp = abs(fe_data_clean_30['caffeine_consumption_time_of_last_drink'].dt.hour - fe_data_clean_30['bedtime_sw'].dt.hour)

fe_data_clean_30['caffeine_consumption_time_of_last_drink'] = temp

fe_data_clean_30 = fe_data_clean_30.rename(columns={'caffeine_consumption_time_of_last_drink': 'hours_between_last_caffeine_and_bedtime'})

In [264]:
fe_data_clean_30.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,difficulty_operating_motor_vehicles_for_long_distances_fosq,difficulty_visiting_family_or_friends_in_their_home_fosq,relationships_with_family_or_friends_affected_fosq,difficulty_watching_a_movie_fosq,difficulty_being_active_in_evening_fosq,difficulty_being_active_in_morning_fosq,effect_on_desire_for_intimacy_or_sex_fosq,fosq_summary_score,type_of_pap_device,ahi
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,2,1,1,2,1.0,1.0,2,8,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,4,3,3,3,3.0,3.0,3,14,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,4,3,4,3,2.0,2.0,4,16,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,4,4,3,3,2.0,2.0,2,15,False,1.3

In [265]:
"""
Cell generated by Data Wrangler.
random last minute cleaning things
"""

def clean_data(fe_data_clean_30):
    # Rename column ('routinely_travel_to_other_time_zones', 'cir_0100') to 'routinely_travel_to_other_time_zones'
    fe_data_clean_30 = fe_data_clean_30.rename(columns={('routinely_travel_to_other_time_zones', 'cir_0100'): 'routinely_travel_to_other_time_zones'})
    # Drop column: 'last_occurance_accident_or_near_miss_due_to_sleepiness'
    fe_data_clean_30 = fe_data_clean_30.drop(columns=['last_occurance_accident_or_near_miss_due_to_sleepiness'])
    return fe_data_clean_30

fe_data_clean_31 = clean_data(fe_data_clean_30.copy())
fe_data_clean_31.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,difficulty_operating_motor_vehicles_for_long_distances_fosq,difficulty_visiting_family_or_friends_in_their_home_fosq,relationships_with_family_or_friends_affected_fosq,difficulty_watching_a_movie_fosq,difficulty_being_active_in_evening_fosq,difficulty_being_active_in_morning_fosq,effect_on_desire_for_intimacy_or_sex_fosq,fosq_summary_score,type_of_pap_device,ahi
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,2,1,1,2,1.0,1.0,2,8,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,4,3,3,3,3.0,3.0,3,14,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,4,3,4,3,2.0,2.0,4,16,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,4,4,3,3,2.0,2.0,2,15,False,1.3

In [266]:
fe_data_clean_31['irreg_sched'] = fe_data_clean_31['irreg_sched'].replace({'<NA>': None})

fe_data_clean_31.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,sw_num_days_per_week,irreg_sched,sw_9am_start_diff,sw_5pm_end_diff,...,difficulty_operating_motor_vehicles_for_long_distances_fosq,difficulty_visiting_family_or_friends_in_their_home_fosq,relationships_with_family_or_friends_affected_fosq,difficulty_watching_a_movie_fosq,difficulty_being_active_in_evening_fosq,difficulty_being_active_in_morning_fosq,effect_on_desire_for_intimacy_or_sex_fosq,fosq_summary_score,type_of_pap_device,ahi
0,58,F,62,168.0,30.7,<NA>,<NA>,None,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,2,1,1,2,1.0,1.0,2,8,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,4,3,3,3,3.0,3.0,3,14,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,4,3,4,3,2.0,2.0,4,16,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,4,4,3,3,2.0,2.0,2,15,False,1.3

In [267]:
null_counts_row = fe_data_clean_31.isnull().sum(axis=1)
thresh = len(fe_data_clean_31.columns) * 0.5

null_counts_row_thresh = null_counts_row > thresh
fe_data_clean_31 = fe_data_clean_31[~null_counts_row_thresh]
fe_data_clean_31 = fe_data_clean_31.reset_index(drop=True)
fe_data_clean_31.info()

# dropped rows with > 50% of the columns missing because they are probably just bad data points

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1784 entries, 0 to 1783
Columns: 196 entries, age to ahi
dtypes: Int32(99), Int64(4), bool(4), boolean(49), datetime64[ns](2), float64(23), object(15)
memory usage: 1.6+ MB

In [269]:
import joblib

save_path = "../data/interim/fe_1_1_1_data.pkl"

joblib.dump(fe_data_clean_31, save_path)

['../data/interim/fe_1_1_1_data.pkl']