# Feature Engineering 1.1.1 Notebook

Using data from 1.0 exploratory data analysis notebook; first iteration of feature engineering

In [23]:
from src.utils import data_utils
import pandas as pd

In [4]:
data = data_utils.load_data("../data/interim/eda_1_0_1_df.pkl")

In [5]:
data.head()

,"(participants_age, modified_dem_0110)","(participants_sex, dem_0500)","(height_in_inches, dem_0610)","(weight_in_pounds, dem_0700)","(body_mass_index_(bmi), dem_0800)","(number_of_people_living_in_your_household, bthbts_0500)","(number_of_children_aged_5_years_or_younger_living_in_your_household, bthbts_0510)","(number_of_children_aged_6_17_living_in_your_household, bthbts_0520)","(number_of_adults_aged_18_59_living_in_your_household, bthbts_0530)","(number_of_adults_aged_60_years_of_older_living_in_your_household, bthbts_0540)",...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,0,0,2,2,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,0,2,1,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,0,0,0,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,1,0,2,0,...,0,0,0,4,4,3,3,1,0,1.3

In [9]:
fe_data = data.copy()

In [12]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data):
    # Rename column ('participants_age', 'modified_dem_0110') to 'age'
    fe_data = fe_data.rename(columns={('participants_age', 'modified_dem_0110'): 'age'})
    # Rename column ('participants_sex', 'dem_0500') to 'sex'
    fe_data = fe_data.rename(columns={('participants_sex', 'dem_0500'): 'sex'})
    # Rename column ('height_in_inches', 'dem_0610') to 'height_inches'
    fe_data = fe_data.rename(columns={('height_in_inches', 'dem_0610'): 'height_inches'})
    # Rename column ('weight_in_pounds', 'dem_0700') to 'weight_pounds'
    fe_data = fe_data.rename(columns={('weight_in_pounds', 'dem_0700'): 'weight_pounds'})
    # Rename column ('body_mass_index_(bmi)', 'dem_0800') to 'bmi'
    fe_data = fe_data.rename(columns={('body_mass_index_(bmi)', 'dem_0800'): 'bmi'})
    return fe_data

fe_data_clean = clean_data(fe_data.copy())
fe_data_clean.head()

,age,sex,height_inches,weight_pounds,bmi,"(number_of_people_living_in_your_household, bthbts_0500)","(number_of_children_aged_5_years_or_younger_living_in_your_household, bthbts_0510)","(number_of_children_aged_6_17_living_in_your_household, bthbts_0520)","(number_of_adults_aged_18_59_living_in_your_household, bthbts_0530)","(number_of_adults_aged_60_years_of_older_living_in_your_household, bthbts_0540)",...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,0,0,2,2,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,0,2,1,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,0,0,0,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,1,0,2,0,...,0,0,0,4,4,3,3,1,0,1.3

In [13]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean):
    # Rename column ('number_of_people_living_in_your_household', 'bthbts_0500') to 'num_people_in_house'
    fe_data_clean = fe_data_clean.rename(columns={('number_of_people_living_in_your_household', 'bthbts_0500'): 'num_people_in_house'})
    # Drop columns: '('number_of_children_aged_5_years_or_younger_living_in_your_household', 'bthbts_0510')', '('number_of_children_aged_6_17_living_in_your_household', 'bthbts_0520')' and 2 other columns
    fe_data_clean = fe_data_clean.drop(columns=[('number_of_children_aged_5_years_or_younger_living_in_your_household', 'bthbts_0510'), ('number_of_children_aged_6_17_living_in_your_household', 'bthbts_0520'), ('number_of_adults_aged_18_59_living_in_your_household', 'bthbts_0530'), ('number_of_adults_aged_60_years_of_older_living_in_your_household', 'bthbts_0540')])
    return fe_data_clean

fe_data_clean_1 = clean_data(fe_data_clean.copy())
fe_data_clean_1.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,"(days_per_week_in_school_or_work, sched_9900)","(irregular_schedule, sched_9910)","(time_school_or_work_starts, sched_9910)","(time_school_or_work_ends, sched_9920)",...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaT,NaT,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,1900-01-01 08:00:00,1900-01-01 17:00:00,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,1900-01-01 07:00:00,1900-01-01 19:00:00,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,1900-01-01 06:00:00,1900-01-01 20:00:00,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,1900-01-01 08:15:00,1900-01-01 17:30:00,...,0,0,0,4,4,3,3,1,0,1.3

In [27]:
""" 
encoding work/school start/end time
turn it into number of hours before/after 9am/5pm 
"""

work_start_times = fe_data_clean_1[('time_school_or_work_starts', 'sched_9910')].dt.time
work_end_times = fe_data_clean_1[('time_school_or_work_ends', 'sched_9920')].dt.time


nine_am = pd.to_datetime("09:00:00").time()
five_pm = pd.to_datetime("17:00:00").time()

def time_diff_in_hours(time1, time2):
    datetime1 = pd.to_datetime(time1, format='%H:%M:%S')
    datetime2 = pd.to_datetime(time2, format='%H:%M:%S')
    diff = (datetime1 - datetime2).total_seconds() / 3600
    return diff

fe_data_clean_1[('work_start_time_diff_from_9am', 'sched_9910')] = work_start_times.apply(lambda x: time_diff_in_hours(x, nine_am))
fe_data_clean_1[('work_end_time_diff_from_5pm', 'sched_9920')] = work_end_times.apply(lambda x: time_diff_in_hours(x, five_pm))

In [29]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(fe_data_clean_1):
    # Rename column ('time_school_or_work_starts', 'sched_9910') to 'sw_9am_diff'
    fe_data_clean_1 = fe_data_clean_1.rename(columns={('time_school_or_work_starts', 'sched_9910'): 'sw_9am_diff'})
    # Rename column ('time_school_or_work_ends', 'sched_9920') to 'sw_5pm_end_diff'
    fe_data_clean_1 = fe_data_clean_1.rename(columns={('time_school_or_work_ends', 'sched_9920'): 'sw_5pm_end_diff'})
    # Rename column 'sw_9am_diff' to 'sw_9am_start_diff'
    fe_data_clean_1 = fe_data_clean_1.rename(columns={'sw_9am_diff': 'sw_9am_start_diff'})
    return fe_data_clean_1

fe_data_clean_2 = clean_data(fe_data_clean_1.copy())
fe_data_clean_2.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,"(days_per_week_in_school_or_work, sched_9900)","(irregular_schedule, sched_9910)",sw_9am_start_diff,sw_5pm_end_diff,...,"(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)","(work_start_time_diff_from_9am, sched_9910)","(work_end_time_diff_from_5pm, sched_9920)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaT,NaT,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3,NaN,NaN
1,30,F,67,188.0,29.4,4,<NA>,False,1900-01-01 08:00:00,1900-01-01 17:00:00,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4,-1.00,0.0
2,30,F,67,165.0,25.8,3,3,True,1900-01-01 07:00:00,1900-01-01 19:00:00,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,-2.00,2.0
3,42,M,64,156.0,26.8,0,7,True,1900-01-01 06:00:00,1900-01-01 20:00:00,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9,-3.00,3.0
4,36,M,63,255.0,45.2,3,5,True,1900-01-01 08:15:00,1900-01-01 17:30:00,...,0,4,4,3,3,1,0,1.3,-0.75,0.5

In [31]:
fe_data_clean_2['sw_9am_start_diff'] = fe_data_clean_2[('work_start_time_diff_from_9am', 'sched_9910')]
fe_data_clean_2['sw_5pm_end_diff'] = fe_data_clean_2[('work_end_time_diff_from_5pm', 'sched_9920')]

fe_data_clean_2 = fe_data_clean_2.drop(columns=[('work_start_time_diff_from_9am', 'sched_9910'), ('work_end_time_diff_from_5pm', 'sched_9920')])

In [32]:
fe_data_clean_2.head()

,age,sex,height_inches,weight_pounds,bmi,num_people_in_house,"(days_per_week_in_school_or_work, sched_9900)","(irregular_schedule, sched_9910)",sw_9am_start_diff,sw_5pm_end_diff,...,"(how_often_do_you_use_your_heated_humidifier, pap_0800)","(how_often_do_you_get_water_in_my_tubing/_mask, pap_1200)","(my_current_mask_type, pap_1300)","(my_mask_size, pap_1400)","(when_was_the_last_time_you_replaced_your_mask, pap_1600)","(when_was_the_last_time_you_checked_or_changed_your_filters, pap_1700)","(when_was_the_last_time_you_checked_or_changed_your_tube, pap_1800)","(how_do_you_feel_about_your_current_mask, pap_1900)","(do_you_use_a_chin_strap, pap_2100)","(apnea_hypopnea_index, ahi)"
0,58,F,62,168.0,30.7,<NA>,<NA>,<NA>,NaN,NaN,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.3
1,30,F,67,188.0,29.4,4,<NA>,False,-1.00,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4
2,30,F,67,165.0,25.8,3,3,True,-2.00,2.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0
3,42,M,64,156.0,26.8,0,7,True,-3.00,3.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.9
4,36,M,63,255.0,45.2,3,5,True,-0.75,0.5,...,0,0,0,4,4,3,3,1,0,1.3